(()=>{
'use strict';

const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const db={
  get(k,d){try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}},
  set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
};

const CFG={
  birthday:'2027-01-25T13:00:00+08:00',
  address:'Jl. Sari Temuku Gg. Sandat, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361, Indonesia',
  villa:'Chandra Villas · Villa 8',
  villaPhone:'+62361738091',
  whatsappOrder:'61432095292',
  doctorAri:'628123924814',
  mobileMedicine:'6281252638533',
  drive:'https://drive.google.com/drive/folders/1RYiTM9qjW5V2a5BqU3W_jYM4suv-54Pi',
  mediaUpload:'https://script.google.com/macros/s/AKfycby5V0h758EFmjZIjKIy_ed4j1B_r5VC32kE-xVoPwqiqE7xaimdMI84IyeMPV68ulCcoA/exec',
  spotify:'https://open.spotify.com/s/P6rY4T0',
  visa:'https://evisa.imigrasi.go.id/',
  levy:'https://lovebali.baliprov.go.id/',
  allIndonesia:'https://allindonesia.imigrasi.go.id/',
  smartraveller:'https://www.smartraveller.gov.au/destinations/asia/indonesia',
  laundry:'https://www.laundrybaliexpress.com/',
  triplej:'https://www.abc.net.au/triplej/live/triplej',
  wise:'https://wise.com/au/travel-money/travel-money-card',
  revolut:'https://www.revolut.com/en-AU/travel/travel-money-card/'
};

const state={
  route:(location.hash.replace('#/','')||'home'),
  profile:db.get('bbb_profile',{name:'Shannon',pin:'',photo:''}),
  plans:db.get('bbb_plans',[]),
  checklist:db.get('bbb_check',{}),
  flight:db.get('bbb_flight',null),
  cart:db.get('bbb_cart',[]),
  drinkCart:db.get('bbb_drink_cart',[]),
  drinkOrders:db.get('bbb_drink_orders',[]),
  bookings:db.get('bbb_bookings',[]),
  modal:null,
  cartOpen:false,
  drinkCartOpen:false,
  drinkClearConfirm:false,
  fx:null
};

const ITINERARY=[
 ['1:00 PM','Arrive & Settle In','Grab a drink, find your people and settle into the villa. DJ live and cocktails flowing.'],
 ['2:00 PM','The B.B.B Bali Games','The less you know, the better. Teams, competition and plenty of laughs. That’s all you’re getting.'],
 ['2:30 PM','Afternoon Canapés','Little bites. Bali style.'],
 ['4:00 PM','Reset & Recharge','Pool, drinks, showers and a little downtime.'],
 ['5:30 PM','Golden Hour Drinks','Cocktails and pre-dinner grazing as the sun starts to drop.'],
 ['7:00 PM','Dinner','A relaxed buffet feast at the villa.'],
 ['8:00 PM','A Little Something Special…','No spoilers. Just be there.'],
 ['8:30 PM','Drinks, Music & Good Times','The night opens up.'],
 ['11:00 PM','That’s a Wrap','Formal event end — unless you’re still talking.']
];

const COCKTAILS=[
 {id:'berry',name:'BERRY BOUJI',type:'Strawberry Daiquiri',desc:'Sweet, frozen and considerably more sophisticated than your decisions will be.',art:'berry'},
 {id:'mint',name:'MINT CONDITION',type:'Mojito',desc:'Fresh, fabulous and holding up remarkably well for fifty.',art:'mint'},
 {id:'after',name:'AFTER HOURS',type:'Espresso Martini',desc:'Because apparently going to bed at a reasonable hour is not on the itinerary.',art:'after'},
 {id:'tropic',name:'TROPIC LIKE IT’S HOT',type:'Piña Colada',desc:'Basically a fruit salad with a drinking problem.',art:'tropic'},
 {id:'mini',name:'MINI BEERS',type:'Licor 43 & Cream',desc:'Tiny beer. Big intentions. Absolutely nothing sensible happens after the first one.',art:'mini'}
];

const MASSAGES=[
 ['Balinese Massage',200000,60],['Relaxing Massage',225000,60],['Foot Reflexology',185000,45],['Anti Stress Massage',185000,45],['Deep Tissue Massage',250000,60],['Four Hand Massage',400000,60],['Thai Massage',250000,60],['Natural Coconut Relaxing Massage',250000,60],['Facial Oriflame',185000,60],['Pedicure',185000,60],['Manicure',185000,60],['Creambath',185000,60],['Head + Foot Massage',250000,60],['Pregnancy Massage',200000,60],['Anti Cellulite Massage',350000,60],['Limfatik Drainase',350000,60],['Hair Braid',125000,45]
].map((x,i)=>({id:'m'+i,name:x[0],price:x[1],mins:x[2]}));
const SLOTS=['10:00 AM','11:30 AM','1:00 PM','2:30 PM','4:00 PM','5:30 PM'];
const FLOATS=[
 ['XL Unicorn','XL','https://static.wixstatic.com/media/cb0458_c6a53918657f48aca29cafad3fd9e946~mv2.jpg/v1/fill/w_700,h_700,al_c,q_85/XL%20Unicorn.jpg'],
 ['XL Flamingo','XL','https://static.wixstatic.com/media/cb0458_0f67bb9988bc4efd9cc9bfebad4a20da~mv2.jpg/v1/fill/w_700,h_700,al_c,q_85/XL%20Flamingo.jpg'],
 ['Pink Flamingo','M','https://static.wixstatic.com/media/cb0458_f8e73b155f8e47ebafb211b582654ff0~mv2.jpg/v1/fill/w_700,h_700,al_c,q_85/M%20Pink%20Flamingo.jpg'],
 ['Pizza Float','M','https://static.wixstatic.com/media/cb0458_e19e860c0a2d43c0b5793eaa787d338d~mv2.jpg/v1/fill/w_700,h_700,al_c,q_85/M%20Pizza%20Matt.jpg']
].map((x,i)=>({id:'f'+i,name:x[0],size:x[1],img:x[2],price:8}));

const READY=[
 ['passport','Passport valid for 6+ months'],['insurance','Travel insurance'],['visa','Visa / e-VOA'],['levy','Bali Tourist Levy'],['arrival','All Indonesia arrival card'],['flight','Flight details added']
];

const GUIDE=[
 ['Before You Fly','Passport, insurance, packing, apps and getting organised.'],
 ['Arrival & Airport','What happens from landing to walking out of the terminal.'],
 ['Getting Around','Drivers, Gojek, Grab, Blue Bird and Bali traffic.'],
 ['Money, Shopping & Essentials','Rupiah, ATMs, money changers, supermarkets and pharmacies.'],
 ['Food, Water & Bali Belly','Drinking water, food safety, hydration and what to do if you get sick.'],
 ['Health & Medical','Doctors, pharmacies, hospitals, medication, sun, mosquitoes and rabies.'],
 ['Safety & Culture','Local laws, respectful travel, temples, ceremonies and staying safe.'],
 ['Staying Longer?','Villa life, laundry, food delivery, private chefs and day trips.'],
 ['Bali Hacks','Useful shortcuts for daily life in Bali.']
];

function persist(){db.set('bbb_profile',state.profile);db.set('bbb_plans',state.plans);db.set('bbb_check',state.checklist);db.set('bbb_flight',state.flight);db.set('bbb_cart',state.cart);db.set('bbb_drink_cart',state.drinkCart);db.set('bbb_drink_orders',state.drinkOrders);db.set('bbb_bookings',state.bookings)}
function money(n,c='IDR'){return c==='AUD'?`$${Number(n).toFixed(2)}`:`Rp${Math.round(n).toLocaleString('id-ID')}`}
function toast(msg){const el=qs('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function navigate(route){state.route=route;state.modal=null;state.cartOpen=false;state.drinkCartOpen=false;location.hash='#/'+route;window.scrollTo({top:0,behavior:'instant'});render()}
window.go=navigate;
window.addEventListener('hashchange',()=>{state.route=location.hash.replace('#/','')||'home';render()});

function renderHeader(){return `<header class="topbar"><div class="brand-mini"><div class="stamp">B.B.B</div><div class="brand-copy"><strong>Nicolle's 50th</strong><span>BALI 2027</span></div></div><button class="btn light" data-action="nav" data-route="profile">${escapeHtml(state.profile?.name||'Guest profile')}</button></header>`}
function renderNav(){const items=[['home','⌂','Home'],['bbb','♠','B.B.B'],['travel','✈','Travel'],['bali','☀','Bali'],['profile','☺','Me']];return `<nav class="navbar" aria-label="Main navigation">${items.map(([r,icon,label])=>`<button class="navitem ${state.route===r?'active':''}" data-action="nav" data-route="${r}"><span class="ico">${icon}</span><span>${label}</span></button>`).join('')}</nav>`}
function page(content,nav=true){return `<div class="shell">${renderHeader()}${content}</div>${nav?renderNav():''}`}
function countdown(){let d=Math.max(0,new Date(CFG.birthday)-new Date()),days=Math.floor(d/864e5);d%=864e5;const h=Math.floor(d/36e5);d%=36e5;const m=Math.floor(d/6e4),s=Math.floor((d%6e4)/1000);return [[days,'Days'],[h,'Hours'],[m,'Mins'],[s,'Secs']].map(x=>`<div class="count"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}

function homeView(){return page(`
<section class="hero"><div class="eyebrow">23–27 January 2027 · Bali</div><h1 class="home-title">Nicolle's<br>50th</h1><div class="bbbline">B.B.B — THE BIG BALI BASH</div><div class="script">Better. Bolder. Boujier.</div><div class="hero-actions"><button class="btn olive" data-action="nav" data-route="bbb">Enter the Big Bali Bash</button><button class="btn outline" data-action="nav" data-route="ready">Get Bali Ready</button></div><div class="countdown" id="countdown">${countdown()}</div></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">Next up</h2><p class="section-sub">The trip, bookings and reminders in one place.</p></div></div><article class="card sunset-card"><img src="/assets/sunset-beanbags.png" alt="Bali beach at sunset with colourful beanbags"><div class="inner"><div class="meta">Sunday 24 January · From 4:00 PM</div><h3>Beanbags, Beers & Sunset</h3><p>The unofficial start to the Bali weekend. Beachside beanbags, sunset drinks and an easy first catch-up.</p><div class="actions"><button class="btn" data-action="modal" data-modal="sunset">View details</button><button class="btn light" data-action="calendar" data-title="Beanbags, Beers & Sunset" data-start="2027-01-24T16:00:00+08:00" data-duration="180">Add to calendar</button></div></div></article></section>
<section class="section"><div class="grid two"><article class="card event-card bbb"><div class="meta">Monday 25 January</div><div style="font-family:'Cormorant Garamond',serif;font-size:64px;line-height:.8;color:var(--brown);margin:22px 0 14px">B.B.B</div><div style="font-size:13px;font-weight:700;letter-spacing:.18em">THE BIG BALI BASH</div><div class="script">Better. Bolder. Boujier.</div><p>Nicolle's 50th. Cocktails, catered food, mystery games and a few surprises.</p><div class="actions"><button class="btn olive" data-action="nav" data-route="bbb">Enter B.B.B</button></div></article><article class="card event-card recovery"><div class="meta">Tuesday 26 January</div><h3>The Great Aussie Recovery</h3><p>Pizza · Pool · Triple J · Massages · Floaties. Same sun. Less effort.</p><div class="actions"><button class="aus-btn red" data-action="nav" data-route="recovery">Enter the Recovery →</button></div></article></div></section>
<section class="section"><div class="grid two"><article class="card"><div class="meta">Bali Ready</div><h3>Travel wallet & reminders</h3><p>Flights, visa, tourist levy, arrival card and the practical things you need before Bali.</p><div class="actions"><button class="btn" data-action="nav" data-route="ready">Open Bali Ready</button></div></article><article class="card"><div class="meta">The B.B.B Media Roll</div><h3>Share the Bali media</h3><p>Keep everyone's photos and videos together in the shared trip folder.</p><div class="actions"><a class="btn olive" href="${CFG.drive}" target="_blank" rel="noopener">View media</a></div></article></div></section>`)}

function bbbView(){return page(`
<section class="bbb-hero"><div class="eyebrow bbb-eyebrow-top">Nicolle's 50th</div><div class="bbbmark">B.B.B</div><div class="submark">THE BIG BALI BASH</div><div class="script">Better. Bolder. Boujier.</div><div class="eyebrow bbb-eyebrow-bottom">Bali 2027</div></section>
<section class="section"><div class="section-head itinerary-head"><div><div class="eyebrow">Monday 25 January</div><h2 class="section-title">The B.B.B itinerary</h2><p class="section-sub">Bring on the big 5-OH.</p></div><button class="btn light itinerary-calendar" data-action="calendar" data-title="Nicolle’s 50th — The Big Bali Bash" data-start="2027-01-25T13:00:00+08:00" data-duration="600">Add to calendar</button></div><div class="timeline">${ITINERARY.map(x=>`<div class="timeline-row"><div class="time">${x[0]}</div><div><h4>${x[1]}</h4><p>${x[2]}</p></div></div>`).join('')}</div></section>
<section class="section cocktail-section"><div class="section-head cocktail-head"><div><div class="eyebrow">Good drinks. Great company.</div><h2 class="section-title">Cocktails</h2><p class="section-sub">Included. Add your drinks to My Order.</p></div><button class="drink-basket-btn ${state.drinkCart.length?'has-items':''}" data-action="drink-cart" aria-label="Open My Order"><span class="drink-basket-icon" aria-hidden="true">🍸</span><span class="drink-basket-label">MY ORDER</span><span class="drink-basket-count" id="drinkCartCount">${state.drinkCart.reduce((n,x)=>n+x.qty,0)}</span></button></div><div class="cocktail-grid">${COCKTAILS.map(c=>{const inOrder=state.drinkCart.find(x=>x.id===c.id),qty=inOrder?.qty||0;return `<article class="cocktail ${inOrder?'in-order':''}" data-cocktail-id="${c.id}"><div class="cocktail-art">${drinkSvg(c.art)}</div><div class="cocktail-body"><h3>${c.name}</h3><div class="type">${c.type}</div><p>${c.desc}</p><div class="orderbar"><div class="qty"><button data-action="drink" data-id="${c.id}" data-delta="-1">−</button><b id="q-${c.id}">${qty}</b><button data-action="drink" data-id="${c.id}" data-delta="1">+</button></div><button class="btn olive add-drink-btn ${inOrder?'added':''}" data-action="order" data-id="${c.id}">${inOrder?'<span class="order-check">✓</span><span>IN MY ORDER</span>':'Add to order'}</button></div></div></article>`}).join('')}</div></section>
<section class="section"><div class="grid two"><article class="card menu-placeholder"><div><div class="eyebrow">2:30 PM</div><h3>Afternoon Canapés</h3><p>Little bites. Bali style.<br><strong>Menu coming soon.</strong></p></div></article><article class="card menu-placeholder"><div><div class="eyebrow">7:00 PM</div><h3>Tonight's Feast</h3><p>A taste of Bali.<br><strong>Full menu coming soon.</strong></p></div></article></div></section>
<section class="section"><div class="grid two"><article class="card"><div class="meta">The B.B.B Playlist</div><h3>Add to the soundtrack</h3><p>Open the shared Spotify playlist and add a song for Bali.</p><div class="actions"><a class="btn olive" href="${CFG.spotify}" target="_blank" rel="noopener">Open Spotify</a></div></article><article class="card bbb-photo-card"><div class="meta">The B.B.B Media Roll</div><h3>Share your media</h3><p>Add your photos and videos to the B.B.B media roll or see what everyone’s been up to.</p><div class="bbb-photo-actions"><button class="btn photo-upload-btn full" data-action="photo-upload" id="bbbMediaUploadBtn">Upload media</button><a class="btn light full" href="${CFG.drive}" target="_blank" rel="noopener">View media</a></div><div class="media-upload-status" id="bbbMediaStatus" aria-live="polite"></div><input id="bbb-photo-upload" class="bbb-photo-input" type="file" accept="image/*,video/*" multiple hidden></article></div></section>
<section class="section"><article class="card"><div class="meta">Location</div><h3>${CFG.villa}</h3><p>${CFG.address}</p><div class="actions"><button class="btn" data-action="maps" data-query="${encodeURIComponent(CFG.address)}">Open in Maps</button><a class="btn light" href="tel:${CFG.villaPhone}">Call villa</a></div></article></section>`)}

function travelView(){return page(`
<section class="pagehead"><div class="eyebrow">Your trip</div><h1>Travel</h1><p>Flights, documents and the practical things you need before Bali.</p></section>
<div class="grid two"><article class="card"><div class="meta">Your flight</div><h3>${state.flight?`${escapeHtml(state.flight.airline)} ${escapeHtml(state.flight.no)}`:'Add your flight'}</h3><p>${state.flight?`${escapeHtml(state.flight.from)} → ${escapeHtml(state.flight.to)}<br>${formatLocal(state.flight.depart)}`:'Save your basic flight details so the app can keep your arrival prep in one place.'}</p><div class="actions"><button class="btn" data-action="modal" data-modal="flight">${state.flight?'Edit flight':'Add flight'}</button>${state.flight?'<button class="btn light" data-action="share-flight">Share flight</button>':''}</div></article><article class="card"><div class="meta">Bali Ready</div><h3>Checklist & documents</h3><p>Visa, levy, arrival card, insurance, passport and flight details.</p><div class="actions"><button class="btn olive" data-action="nav" data-route="ready">Open Bali Ready</button></div></article></div>
<section class="section"><article class="card"><div class="meta">Your Bali base</div><h3>Chandra Villas</h3><p>High-end villas with kitchens, butler service and private pools, plus complimentary breakfast.</p><p style="margin-top:12px">${CFG.address}</p><div class="actions"><button class="btn" data-action="maps" data-query="${encodeURIComponent(CFG.address)}">Open in Maps</button><a class="btn light" href="tel:${CFG.villaPhone}">Call villa</a></div></article></section>`)}

function readyView(){const done=READY.filter(x=>state.checklist[x[0]]).length,pct=Math.round(done/READY.length*100);return page(`
<section class="pagehead"><div class="eyebrow">Bali Ready</div><h1>Ready to go?</h1><p>Keep every important travel job clear, linked and easy to check off.</p></section>
<article class="card"><div class="meta">Your progress</div><h3>${pct}% ready</h3><div class="progress"><div style="width:${pct}%"></div></div><p>${pct===100?'You’re Bali ready 🌴':'Tick each item off as you organise it.'}</p></article>
<section class="section"><div class="ready-grid">${READY.map(x=>`<label class="card check-card"><input type="checkbox" data-action="ready" data-key="${x[0]}" ${state.checklist[x[0]]?'checked':''}><div><div class="meta">${state.checklist[x[0]]?'Complete':'To do'}</div><h3 style="font-size:27px;margin-bottom:0">${x[1]}</h3></div></label>`).join('')}</div></section>
<section class="section"><div class="grid two"><article class="card"><div class="meta">1 · Visa / e-VOA</div><h3>Do this first</h3><p>For a short visit, the 30-day B1 e-VOA can be applied for online. Check every passport detail before paying. Save the visa to your phone as a backup.</p><div class="actions"><a class="btn olive" href="${CFG.visa}" target="_blank">Official e-Visa site</a><button class="btn light" data-action="modal" data-modal="visaHelp">How to apply</button></div></article><article class="card"><div class="meta">2 · Tourist Levy</div><h3>Bali Tourist Levy</h3><p>Complete the Bali levy before travel and keep the QR code on your phone in case it is requested.</p><div class="actions"><a class="btn olive" href="${CFG.levy}" target="_blank">Official Love Bali site</a></div></article><article class="card"><div class="meta">3 · Arrival declaration</div><h3>All Indonesia</h3><p>Complete it within three days of arrival. It combines immigration, customs and health declarations and gives you a QR code.</p><div class="actions"><a class="btn olive" href="${CFG.allIndonesia}" target="_blank">Open All Indonesia</a></div></article><article class="card"><div class="meta">Medication & entry rules</div><h3>Check before you pack</h3><p>If you take medication, speak to your doctor and carry supporting documentation. Check current Indonesian entry and medication guidance before travel.</p><div class="actions"><a class="btn" href="${CFG.smartraveller}" target="_blank">Smartraveller Indonesia</a></div></article></div></section>
<section class="section"><article class="card"><div class="meta">Travel wallet</div><h3>Keep your confirmations together</h3><p>Save your visa, levy QR and All Indonesia QR in your phone's Files/Wallet and keep offline copies. This app can track completion, but does not store sensitive travel documents in the demo.</p></article></section>`)}

function baliView(){return page(`
<section class="pagehead"><div class="eyebrow">Useful in Bali</div><h1>Bali Basics</h1><p>The useful stuff, without turning the birthday app into a travel textbook.</p></section>
<article class="card weather" id="weather"><div class="meta">Live Seminyak weather</div><h3>Loading weather…</h3></article>
<section class="section"><article class="card fx-card"><div class="meta">Live currency</div><h3>AUD ↔ IDR</h3><div class="converter"><div class="money-field"><label>Australian dollars</label><div class="money-input"><input id="aud" type="number" value="10" inputmode="decimal"><span>AUD</span></div></div><button class="swap" data-action="swap-fx" aria-label="Swap currency">↕</button><div class="money-field"><label>Indonesian rupiah</label><div class="money-input"><input id="idr" type="number" inputmode="numeric"><span>IDR</span></div></div></div><p id="fxnote" style="margin-top:14px">Loading live indicative rate…</p></article></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">Quick help</h2><p class="section-sub">Useful contacts when you need them.</p></div></div><div class="help-grid"><article class="card help-card"><div><div class="meta">Medical</div><h3>Dr Ari</h3><p>Medical assistance via WhatsApp.</p></div><a class="btn" href="https://wa.me/${CFG.doctorAri}" target="_blank">WhatsApp Dr Ari</a></article><article class="card help-card"><div><div class="meta">Medical clinic</div><h3>Mobile Medicine</h3><p>Medical Clinic · WhatsApp.</p></div><a class="btn" href="https://wa.me/${CFG.mobileMedicine}" target="_blank">WhatsApp clinic</a></article><article class="card help-card"><div><div class="meta">Laundry</div><h3>Laundry Delivery</h3><p>Laundry Bali Express pickup and delivery service.</p></div><a class="btn" href="${CFG.laundry}" target="_blank">Open service</a></article><article class="card help-card"><div><div class="meta">Money</div><h3>Travel Card Options</h3><p>Explore Wise and Revolut as travel card options.</p></div><button class="btn" data-action="modal" data-modal="cards">View options</button></article></div></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">Find near me</h2><p class="section-sub">Whatever you need, close by.</p></div></div><div class="findgrid">${['Pharmacy','ATM','Convenience store','Supermarket','Medical clinic','Hospital','Money changer','Coffee','Food','Beach','Petrol station'].map(x=>`<button class="find-btn" data-action="near" data-query="${x}">${x}<small>Search nearby →</small></button>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">The Bali Guide</h2><p class="section-sub">Short, useful guides you can open when you need them.</p></div></div><div class="guide-grid">${GUIDE.map((g,i)=>`<button class="guide-btn" data-action="guide" data-index="${i}">${g[0]}<small>${g[1]}</small></button>`).join('')}</div></section>`)}

function profileView(){return page(`
<section class="pagehead"><div class="eyebrow">Your space</div><h1>My Profile</h1><p>Your profile, bookings and trip plans.</p></section>
<article class="card profile-card"><div class="avatar">${state.profile.photo?`<img src="${state.profile.photo}" alt="Profile photo">`:'☺'}</div><div><h3>${escapeHtml(state.profile.name||'Guest')}</h3><p>Your profile is saved on this device.</p></div></article>
<section class="section"><article class="card"><div class="form"><div class="field"><label>Name</label><input id="pname" value="${escapeAttr(state.profile.name||'')}"></div><div class="field"><label>4-digit PIN</label><input id="ppin" inputmode="numeric" maxlength="4" value="${escapeAttr(state.profile.pin||'')}" placeholder="1234"></div><div class="field"><label>Profile photo</label><label class="btn light file-btn">Add / change photo<input id="pphoto" type="file" accept="image/*"></label></div><button class="btn full" data-action="save-profile">Save profile</button></div></article></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">My Plans</h2></div></div>${state.plans.length?state.plans.map((p,i)=>`<article class="card plan" style="margin-bottom:12px"><div><div class="meta">${p.pay==='cash'?'Cash on the day':p.pay==='free'?'RSVP':'Booked'}</div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.meta||'')}</p></div><button class="btn light" data-action="cancel-plan" data-index="${i}">Cancel</button></article>`).join(''):'<article class="card"><p>Nothing booked yet.</p></article>'}</section>
<section class="section"><div class="section-head"><div><h2 class="section-title">My Orders</h2><p class="section-sub">Your B.B.B cocktail order history.</p></div></div>${state.drinkOrders.length?state.drinkOrders.map(o=>`<article class="card previous-order"><div class="meta">${formatOrderTime(o.sentAt)}</div>${o.items.map(x=>`<div class="previous-order-line"><b>${x.qty} × ${escapeHtml(x.name)}</b><span>${escapeHtml(x.type)}</span></div>`).join('')}<div class="previous-order-total">${o.items.reduce((n,x)=>n+x.qty,0)} drink${o.items.reduce((n,x)=>n+x.qty,0)===1?'':'s'}</div></article>`).join(''):'<article class="card"><p>No cocktail orders yet.</p></article>'}</section>`)}

function recoveryView(){return `<div class="recovery-shell"><div class="shell"><div class="recovery-top"><button class="aus-btn" data-action="nav" data-route="home">← Back</button><button class="aus-btn red" data-action="cart">Cart (${state.cart.length})</button></div><section class="recovery-hero"><div class="recovery-kicker">AUSTRALIA DAY · 26 JANUARY 2027 · BALI</div><h1 class="recovery-title">The Great Aussie Recovery</h1><div class="recovery-tag">Same Sun. Less Effort.</div><p>Pizza · Pool · Triple J · Massages · Floaties</p></section><section class="section"><article class="card recovery-card"><div class="meta">Tuesday 26 January · From 10:00 AM</div><h3>Relax. Recover. Recharge.</h3><p>Yesterday was the Big Bali Bash. Today, we recover. Come for everything or only the part you want.</p><div class="actions"><button class="aus-btn" data-action="modal" data-modal="recoveryIt">View itinerary</button><a class="aus-btn yellow" href="${CFG.triplej}" target="_blank">Listen live to Triple J</a><button class="aus-btn yellow" data-action="calendar" data-title="The Great Aussie Recovery" data-start="2027-01-26T10:00:00+08:00" data-duration="600">Add to calendar</button></div></article></section><section class="section"><div class="grid two"><article class="card recovery-card"><div class="meta">1:00–3:00 PM</div><h3>🍕 Bali Pizza Party</h3><p>Fresh pizza at the villa. Rp249,000 per person.</p><div class="actions"><button class="aus-btn red" data-action="modal" data-modal="pizzaInfo">See menu & book</button></div></article><article class="card recovery-card"><div class="meta">10:00 AM onwards</div><h3>💆 Massage & Spa</h3><p>Choose a treatment, then choose a time. Four appointments are available per block.</p><div class="actions"><button class="aus-btn" data-action="nav" data-route="massage">Book massage</button></div></article><article class="card recovery-card"><div class="meta">Pool day</div><h3>🏖 Float Hire</h3><p>Browse the float catalogue on its own screen and add your pick to the cart.</p><div class="actions"><button class="aus-btn yellow" data-action="nav" data-route="floats">Choose your float</button></div></article></div></section></div></div>${renderNav()}`}

function massageView(){return `<div class="recovery-shell"><div class="shell">${renderHeader()}<section class="pagehead"><div class="eyebrow">The Great Aussie Recovery</div><h1>Massage & Spa</h1><p>Choose your treatment first, then select a time block. Payment is cash on the day.</p></section><article class="card recovery-card"><div class="field"><label>Treatment</label><select id="mtreat">${MASSAGES.map(x=>`<option value="${x.id}">${x.name} · ${x.mins} min · ${money(x.price)}</option>`).join('')}</select></div><div class="section" style="margin-top:24px"><div class="meta">Available times</div><div class="slotgrid" style="margin-top:12px">${SLOTS.map(x=>{const used=state.bookings.filter(b=>b.slot===x&&b.status!=='cancelled').length;return `<button class="slot" data-action="slot" data-slot="${x}" ${used>=4?'disabled':''}><b>${x}</b><span>${Math.max(0,4-used)} spots left</span></button>`}).join('')}</div></div><input id="mslot" type="hidden"><div class="actions" style="margin-top:24px"><button class="aus-btn" data-action="confirm-massage">Confirm · Cash on the day</button><button class="aus-btn yellow" data-action="nav" data-route="recovery">Back to Recovery</button></div></article></div></div>${renderNav()}`}

function floatsView(){return `<div class="recovery-shell"><div class="shell">${renderHeader()}<section class="pagehead"><div class="eyebrow">The Great Aussie Recovery</div><h1>Choose Your Float</h1><p>Browse the real supplier imagery, choose your float and add it to your Recovery cart.</p></section><div class="productgrid">${FLOATS.map(f=>`<article class="product"><img src="${f.img}" alt="${f.name}" loading="lazy"><div class="productbody"><h4>${f.name}</h4><p>${f.size} · 24-hour hire</p><div class="price">From ${money(f.price,'AUD')}</div><button class="aus-btn yellow" data-action="add-float" data-id="${f.id}">Add to cart</button></div></article>`).join('')}</div><div class="actions" style="margin-top:24px"><button class="aus-btn" data-action="nav" data-route="recovery">← Back to Recovery</button></div></div></div>${renderNav()}`}

function modalHtml(type){
 if(type==='sunset')return `<div class="eyebrow">Sunday 24 January · From 4:00 PM</div><h2>Beanbags, Beers & Sunset</h2><img src="/assets/sunset-beanbags.png" alt="Bali beach at sunset" style="border-radius:22px;margin:12px 0 20px"><p>The unofficial start to the Bali weekend. We’ll organise beachside beanbags, sunset drinks and an easy first catch-up. Totally optional — come for one drink or stay for sunset.</p><div class="sunset-actions"><button class="btn olive full" data-action="rsvp-sunset">I'm in</button><button class="btn light full" data-action="calendar" data-title="Beanbags, Beers & Sunset" data-start="2027-01-24T16:00:00+08:00" data-duration="180">+ Add to calendar</button><button class="text-close" data-action="close-modal">Close</button></div>`;
 if(type==='flight')return `<div class="eyebrow">My flight</div><h2>Flight details</h2><div class="form"><div class="field"><label>Airline</label><input id="fair" value="${escapeAttr(state.flight?.airline||'')}" placeholder="Jetstar"></div><div class="field"><label>Flight number</label><input id="fno" value="${escapeAttr(state.flight?.no||'')}" placeholder="JQ116"></div><div class="grid two"><div class="field"><label>From</label><input id="ffrom" value="${escapeAttr(state.flight?.from||'')}" placeholder="PER"></div><div class="field"><label>To</label><input id="fto" value="${escapeAttr(state.flight?.to||'DPS')}" placeholder="DPS"></div></div><div class="field"><label>Departure date & time</label><input id="fdep" type="datetime-local" value="${state.flight?.depart||''}"></div><div class="field"><label>Arrival date & time</label><input id="farr" type="datetime-local" value="${state.flight?.arrive||''}"></div><div class="actions"><button class="btn olive" data-action="save-flight">Save flight</button><button class="btn light" data-action="close-modal">Cancel</button></div></div>`;
 if(type==='cards')return `<div class="eyebrow">Money in Bali</div><h2>Travel Card Options</h2><div class="grid two"><article class="card"><h3>Wise</h3><p>Multi-currency travel card and app.</p><div class="actions"><a class="btn" href="${CFG.wise}" target="_blank">Visit Wise</a></div></article><article class="card"><h3>Revolut</h3><p>Travel card and app for managing currencies.</p><div class="actions"><a class="btn" href="${CFG.revolut}" target="_blank">Visit Revolut</a></div></article></div><div class="actions"><button class="btn light" data-action="close-modal">Close</button></div>`;
 if(type==='pizzaInfo')return `<div class="eyebrow">Tuesday 26 January · 1:00–3:00 PM</div><h2>Bali Pizza Party 🍕</h2><div class="price" style="font-size:28px">Rp249,000 per person</div><p>Fresh pizza served at the villa as part of The Great Aussie Recovery.</p><div class="pizza-step"><b>WHAT'S INCLUDED</b><p>6 classic pizzas · 2 specialty pizzas · Nutella & fresh fruit dessert pizza.</p></div><div class="actions"><button class="aus-btn red" data-action="modal" data-modal="pizzaMenu">View the menu →</button><button class="aus-btn" data-action="close-modal">Back</button></div>`;
 if(type==='pizzaMenu')return `<div class="eyebrow">Bali Pizza Party</div><h2>The Menu</h2><div class="pizza-step"><b>6 CLASSIC PIZZAS</b><p>Pizza names and ingredients to be added once the supplier confirms them.</p></div><div class="pizza-step"><b>2 SPECIALTY PIZZAS</b><p>Pizza names and ingredients to be added once the supplier confirms them.</p></div><div class="pizza-step"><b>DESSERT PIZZA</b><p>Nutella & fresh fruit pizza.</p></div><div class="field"><label>People</label><input id="pizzaqty" type="number" min="1" value="1"></div><div class="actions"><button class="aus-btn red" data-action="add-pizza">Add to cart · Rp249K pp</button><button class="aus-btn" data-action="modal" data-modal="pizzaInfo">← Back</button></div>`;
 if(type==='recoveryIt')return `<div class="eyebrow">Tuesday 26 January 2027</div><h2>Recovery itinerary</h2><div class="timeline">${[['10:00 AM','Massage & Spa Bookings Commence'],['11:00 AM','The Great Aussie Recovery Begins'],['11:00 AM–1:00 PM','Pool, Music, Drinks & Chill'],['1:00 PM','Bali Pizza Party Begins'],['1:00 PM–3:00 PM','Pizza Party'],['3:00 PM','Pizza Party Finishes'],['3:00 PM–4:00 PM','Pool, Triple J & Recovery Mode'],['4:00 PM onwards','No Schedule']].map(x=>`<div class="timeline-row"><div class="time">${x[0]}</div><div><h4>${x[1]}</h4></div></div>`).join('')}</div><div class="actions"><button class="aus-btn" data-action="close-modal">Close</button></div>`;
 if(type==='visaHelp')return `<div class="eyebrow">Visa / e-VOA</div><h2>How to apply</h2><div class="pizza-step"><b>1. Choose the correct visa</b><p>For a short tourist stay, select the 30-day B1 option if it suits your trip.</p></div><div class="pizza-step"><b>2. Prepare your documents</b><p>Passport data page with at least six months validity, photograph and outbound/onward ticket where requested.</p></div><div class="pizza-step"><b>3. Enter your details carefully</b><p>Check passport number, name, dates and address in Indonesia before paying. Wrong information can delay entry and may require another application.</p></div><div class="pizza-step"><b>4. Pay and save your visa</b><p>Once approved, save a copy to your phone. It is electronically linked to your passport but keeping a backup is sensible.</p></div><div class="actions"><a class="btn olive" href="${CFG.visa}" target="_blank">Open official site</a><button class="btn light" data-action="close-modal">Done</button></div>`;
 if(type.startsWith('guide-')){const i=Number(type.split('-')[1]),g=GUIDE[i];return `<div class="eyebrow">The Bali Guide</div><h2>${g[0]}</h2><p>${g[1]}</p>${guideContent(i)}<div class="actions"><button class="btn" data-action="close-modal">Done</button></div>`}
 return '';
}

function renderModal(){qsa('.overlay,.modal').forEach(x=>x.remove());if(!state.modal)return;document.body.insertAdjacentHTML('beforeend',`<div class="overlay" data-action="close-modal"></div><div class="modal"><div class="modal-card">${modalHtml(state.modal)}</div></div>`)}
function renderCart(){qsa('.drawer,.cart-overlay').forEach(x=>x.remove());if(!state.cartOpen)return;document.body.insertAdjacentHTML('beforeend',`<div class="overlay cart-overlay" data-action="close-cart"></div><aside class="drawer"><div class="section-head"><h2 class="section-title">Recovery Cart</h2><button class="btn light" data-action="close-cart">Close</button></div>${state.cart.length?state.cart.map((x,i)=>`<div class="cartline"><div><b>${escapeHtml(x.title)}</b><small>${escapeHtml(x.meta||'')}</small></div><div><b>${money(x.price,x.currency)}</b><br><button class="btn light" data-action="remove-cart" data-index="${i}" style="margin-top:7px;padding:8px 10px;min-height:0">Remove</button></div></div>`).join(''):'<p>Your cart is empty.</p>'}<div class="actions"><button class="aus-btn red full" data-action="save-cart">Save to My Plans</button></div><p style="font-size:12px;color:var(--muted)">Online payments can be connected once Stripe is ready.</p></aside>`)}

function renderDrinkCart(){qsa('.drink-drawer,.drink-cart-overlay').forEach(x=>x.remove());if(!state.drinkCartOpen)return;const photo=state.profile.photo?`<img src="${state.profile.photo}" alt="${escapeAttr(state.profile.name||'Guest')} profile photo">`:'☺',total=state.drinkCart.reduce((n,x)=>n+x.qty,0);document.body.insertAdjacentHTML('beforeend',`<div class="overlay drink-cart-overlay" data-action="close-drink-cart"></div><aside class="drawer drink-drawer"><div class="section-head"><div><div class="eyebrow">B.B.B cocktails</div><h2 class="section-title">My Order</h2></div><button class="btn light" data-action="close-drink-cart">Close</button></div><div class="drink-profile"><div class="drink-profile-photo">${photo}</div><div><div class="meta">Ordering as</div><h3>${escapeHtml(state.profile.name||'Guest')}</h3></div></div>${state.drinkCart.length?state.drinkCart.map((x,i)=>`<div class="drink-cartline"><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.type)}</small></div><div class="drink-cart-controls"><button data-action="drink-cart-qty" data-index="${i}" data-delta="-1">−</button><b>${x.qty}</b><button data-action="drink-cart-qty" data-index="${i}" data-delta="1">+</button><button class="remove-drink" data-action="remove-drink-cart" data-index="${i}">Remove</button></div></div>`).join(''):'<p>Your cocktail order is empty.</p>'}${state.drinkCart.length?`<div class="actions drink-place-actions"><button class="btn olive full" data-action="place-drink-order">Send order to the bar</button></div><p class="drink-order-note">Your order will open directly in WhatsApp to the B.B.B bartenders.</p>${state.drinkClearConfirm?`<div class="clear-order-confirm"><div class="clear-order-icon">↺</div><h3>Clear your order?</h3><p>This will remove all ${total} drink${total===1?'':'s'} from My Order.</p><div class="clear-order-actions"><button class="btn light" data-action="cancel-clear-drink-order">Keep order</button><button class="btn clear-confirm-btn" data-action="clear-drink-order">Yes, clear it</button></div></div>`:`<button class="clear-drink-order clear-attention" data-action="confirm-clear-drink-order"><span class="clear-order-symbol">↺</span><span>CLEAR MY ORDER</span></button>`}`:''}</aside>`) }

function render(){const app=qs('#app');if(!app)return;try{switch(state.route){case'bbb':app.innerHTML=bbbView();break;case'travel':app.innerHTML=travelView();break;case'ready':app.innerHTML=readyView();break;case'bali':app.innerHTML=baliView();setTimeout(()=>{loadWeather();loadFx()},10);break;case'profile':app.innerHTML=profileView();break;case'recovery':app.innerHTML=recoveryView();break;case'massage':app.innerHTML=massageView();break;case'floats':app.innerHTML=floatsView();break;default:app.innerHTML=homeView()}renderModal();renderCart();renderDrinkCart()}catch(err){console.error(err);app.innerHTML=`<div class="shell"><div class="card" style="margin-top:40px"><h3>App loading issue</h3><p>Please refresh. If this persists, send the browser Console error.</p></div></div>`}}

function openModal(type){state.modal=type;renderModal()}
function closeModal(){state.modal=null;renderModal()}
function drinkSvg(type){const common=`<svg viewBox="0 0 260 220" role="img" aria-label="Illustrated cocktail">`;
 if(type==='berry')return common+`<ellipse cx="130" cy="184" rx="54" ry="7" fill="#d9b89c" opacity=".35"/><path d="M61 54h138l-39 74h-60z" fill="#d65a55" stroke="#6b4e3d" stroke-width="3"/><path d="M130 128v46M101 176h58" stroke="#6b4e3d" stroke-width="5" stroke-linecap="round"/><circle cx="184" cy="49" r="22" fill="#c9443d"/><path d="M174 30l12-10 8 13" fill="#556b3f"/><path d="M191 53l22-15" stroke="#7d9a53" stroke-width="6"/>`+`</svg>`;
 if(type==='mint')return common+`<rect x="88" y="45" width="84" height="124" rx="8" fill="#e8f0d8" stroke="#6b4e3d" stroke-width="3"/><circle cx="112" cy="76" r="17" fill="#b7cf83"/><circle cx="145" cy="119" r="18" fill="#b7cf83"/><path d="M112 76l58 82M146 34c-22 9-34 27-30 46M153 39c20 9 26 29 17 45" stroke="#556b3f" stroke-width="7" stroke-linecap="round"/><path d="M166 28l-20 139" stroke="#b68652" stroke-width="5"/>`+`</svg>`;
 if(type==='after')return common+`<ellipse cx="130" cy="186" rx="55" ry="7" fill="#d9b89c" opacity=".35"/><path d="M59 62h142l-43 70h-56z" fill="#3b251b" stroke="#6b4e3d" stroke-width="3"/><path d="M61 62c30-17 108-17 138 0" fill="#ead7bb"/><path d="M130 132v43M102 177h56" stroke="#6b4e3d" stroke-width="5" stroke-linecap="round"/><ellipse cx="116" cy="59" rx="8" ry="4" fill="#3a241a"/><ellipse cx="135" cy="57" rx="8" ry="4" fill="#3a241a"/><ellipse cx="153" cy="60" rx="8" ry="4" fill="#3a241a"/>`+`</svg>`;
 if(type==='tropic')return common+`<ellipse cx="128" cy="190" rx="55" ry="7" fill="#d9b89c" opacity=".35"/><path d="M88 54h84l-8 111c-1 14-68 14-69 0z" fill="#f1dc9b" stroke="#6b4e3d" stroke-width="3"/><path d="M88 54c20-12 64-12 84 0" fill="#fff1c7"/><path d="M157 39l27-17 13 28-30 15" fill="#e7b22c" stroke="#6b4e3d" stroke-width="2"/><circle cx="169" cy="47" r="18" fill="none" stroke="#7f9c51" stroke-width="6"/><path d="M107 41c-9-17-4-32 12-41M116 42c2-19 13-31 31-36" stroke="#556b3f" stroke-width="7" stroke-linecap="round"/>`+`</svg>`;
 return common+`<rect x="63" y="69" width="56" height="78" rx="10" fill="#e9a927" stroke="#6b4e3d" stroke-width="3"/><rect x="141" y="69" width="56" height="78" rx="10" fill="#e9a927" stroke="#6b4e3d" stroke-width="3"/><rect x="64" y="69" width="54" height="20" rx="9" fill="#fff7e8"/><rect x="142" y="69" width="54" height="20" rx="9" fill="#fff7e8"/><path d="M119 92h15c14 0 14 28 0 28h-15M197 92h15c14 0 14 28 0 28h-15" fill="none" stroke="#6b4e3d" stroke-width="3"/>`+`</svg>`;
}

function guideContent(i){const data=[
 `<div class="pizza-step"><b>ESSENTIALS</b><p>Travel insurance is essential. Make sure your passport has at least six months validity from entry. Keep digital and physical copies of key documents.</p></div><div class="pizza-step"><b>PACKING</b><p>Light clothing, bathers, sunscreen, sanitary items, Panadol/Nurofen, Hydralyte, GastroStop/Imodium, thongs, a hat, a nice shirt and closed shoes for men for venues with dress standards. Carry-on liquids must follow airline limits.</p></div>`,
 `<div class="pizza-step"><b>ARRIVAL FLOW</b><p>Follow signs for Imigrasi / Immigration. Use the e-gates where eligible and scan the passport linked to your visa. If a machine is touchy, hold the passport steady and try again or use another machine.</p></div><div class="pizza-step"><b>AFTER IMMIGRATION</b><p>Collect bags, follow the crowd toward customs/exit and have your All Indonesia QR ready. Keep your Bali levy QR available in case it is requested.</p></div>`,
 `<div class="pizza-step"><b>TRAFFIC</b><p>Bali traffic can make short distances take much longer than expected. Allow buffer time for airport runs, dinners and bookings.</p></div><div class="pizza-step"><b>OPTIONS</b><p>Gojek, Grab, Blue Bird taxis and private drivers are common options. Use reputable providers and check the plate/driver before getting in.</p></div>`,
 `<div class="pizza-step"><b>MONEY</b><p>Carry some Indonesian Rupiah. Use reputable or bank-attached ATMs and established money changers. Avoid handing your card out of sight.</p></div><div class="pizza-step"><b>EVERYDAY ESSENTIALS</b><p>Guardian and other pharmacies are useful for basic medicines and toiletries. Convenience stores and supermarkets are easy to find in Seminyak.</p></div>`,
 `<div class="pizza-step"><b>WATER</b><p>Do not drink tap water. Use bottled or properly filtered water and stay hydrated in the heat.</p></div><div class="pizza-step"><b>IF YOU GET SICK</b><p>Use Hydralyte, rest and seek medical help for severe, persistent or worrying symptoms. Dr Ari and Mobile Medicine are linked in Quick Help.</p></div>`,
 `<div class="pizza-step"><b>MEDICAL</b><p>Private medical care is available, but travel insurance matters. Keep medication in original packaging where possible and travel with supporting documentation for prescription medicines.</p></div><div class="pizza-step"><b>MOSQUITOES & ANIMALS</b><p>Use insect repellent and avoid handling stray animals. Seek prompt medical advice after animal bites or scratches.</p></div>`,
 `<div class="pizza-step"><b>LAW & RESPECT</b><p>Indonesian law applies. Be respectful around temples, ceremonies and offerings. Dress appropriately at religious sites and follow local instructions.</p></div><div class="pizza-step"><b>NIGHT SAFETY</b><p>Use reputable transport, watch drinks and valuables, and avoid unnecessary risk on roads or scooters.</p></div>`,
 `<div class="pizza-step"><b>VILLA LIFE</b><p>Laundry pickup, food delivery, private chefs, spa services and drivers can make longer stays easy. Construction and traffic can vary by area.</p></div>`,
 `<div class="pizza-step"><b>USEFUL SHORTCUTS</b><p>Keep WhatsApp, Gojek, Grab/Blue Bird, maps and your banking/travel-card apps ready. Carry a power bank, electrolytes and a small amount of cash.</p></div>`
 ];return data[i]||''}

async function loadWeather(){const el=qs('#weather');if(!el)return;try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=-8.691&longitude=115.166&current=temperature_2m,relative_humidity_2m,precipitation&daily=temperature_2m_max,precipitation_probability_max&timezone=Asia%2FMakassar&forecast_days=7');if(!r.ok)throw new Error('weather');const d=await r.json();el.innerHTML=`<div class="meta">Live Seminyak weather</div><div class="weather-top"><div><div class="temp">${Math.round(d.current.temperature_2m)}°</div><p>${d.current.relative_humidity_2m}% humidity · ${d.current.precipitation}mm rain now</p></div><span class="tag">Bali time</span></div><div class="forecast">${d.daily.time.map((x,i)=>`<div>${new Date(x+'T00:00:00').toLocaleDateString(undefined,{weekday:'short'})}<b>${Math.round(d.daily.temperature_2m_max[i])}°</b><small>${d.daily.precipitation_probability_max[i]||0}% rain</small></div>`).join('')}</div>`}catch{el.innerHTML='<div class="meta">Live Seminyak weather</div><h3>Weather unavailable</h3><p>Try again when you have a connection.</p>'}}
async function loadFx(){try{const r=await fetch('https://api.frankfurter.app/latest?from=AUD&to=IDR');if(!r.ok)throw new Error('fx');const d=await r.json();state.fx=d.rates.IDR;convertFx('aud')}catch{const n=qs('#fxnote');if(n)n.textContent='Live rate unavailable. Try again later.'}}
function convertFx(src){if(!state.fx)return;const aud=qs('#aud'),idr=qs('#idr'),note=qs('#fxnote');if(!aud||!idr)return;if(src==='aud')idr.value=Math.round((Number(aud.value)||0)*state.fx);else aud.value=((Number(idr.value)||0)/state.fx).toFixed(2);if(note)note.textContent=`Live indicative rate: 1 AUD ≈ ${Math.round(state.fx).toLocaleString()} IDR. Your bank or money changer may differ.`}

function addCalendar(title,start,dur){const s=new Date(start),e=new Date(s.getTime()+Number(dur||60)*60000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${fmt(s)}\nDTEND:${fmt(e)}\nSUMMARY:${title}\nLOCATION:${CFG.address}\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='bbb-bali.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function saveFlight(){const fields=['fair','fno','ffrom','fto','fdep','farr'].map(id=>qs('#'+id));if(fields.some(x=>!x||!x.value.trim()))return toast('Complete all flight fields');state.flight={airline:fields[0].value.trim(),no:fields[1].value.trim(),from:fields[2].value.trim().toUpperCase(),to:fields[3].value.trim().toUpperCase(),depart:fields[4].value,arrive:fields[5].value};state.checklist.flight=true;persist();closeModal();render();toast('Flight saved')}
async function shareFlight(){if(!state.flight)return;const f=state.flight,text=`${state.profile.name||'Guest'}'s Bali flight ✈️\n${f.airline} ${f.no}\n${f.from} → ${f.to}\nDeparts ${formatLocal(f.depart)}\nLands ${formatLocal(f.arrive)}`;if(navigator.share){try{await navigator.share({title:'My Bali flight',text})}catch{}}else{await navigator.clipboard?.writeText(text);toast('Flight details copied')}}
function saveProfile(){const name=qs('#pname')?.value.trim(),pin=qs('#ppin')?.value.trim();if(!name)return toast('Add your name');if(pin&&!/^\d{4}$/.test(pin))return toast('PIN must be 4 digits');const file=qs('#pphoto')?.files?.[0];const done=photo=>{state.profile={...state.profile,name,pin,photo:photo||state.profile.photo};persist();render();toast('Profile saved')};if(!file)return done();const reader=new FileReader();reader.onload=()=>done(reader.result);reader.readAsDataURL(file)}
function animateDrinkToBasket(id){const card=qs(`[data-cocktail-id="${id}"]`),source=card?.querySelector('.cocktail-art svg'),basket=qs('.drink-basket-btn');if(!source||!basket)return;basket.classList.add('has-items');const sr=source.getBoundingClientRect();requestAnimationFrame(()=>{const br=basket.getBoundingClientRect();if(!br.width||!br.height)return;const flyer=document.createElement('div');flyer.className='drink-flyer';flyer.innerHTML=source.outerHTML;const size=Math.min(92,Math.max(64,sr.width*.34));flyer.style.width=size+'px';flyer.style.height=size+'px';flyer.style.left=(sr.left+sr.width/2-size/2)+'px';flyer.style.top=(sr.top+sr.height/2-size/2)+'px';document.body.appendChild(flyer);const dx=br.left+br.width/2-(sr.left+sr.width/2),dy=br.top+br.height/2-(sr.top+sr.height/2);const anim=flyer.animate([{transform:'translate(0,0) scale(.72)',opacity:0},{transform:'translate(0,-12px) scale(1.06)',opacity:1,offset:.18},{transform:`translate(${dx}px,${dy}px) scale(.28)`,opacity:.95}],{duration:720,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'});anim.onfinish=()=>{flyer.remove();basket.classList.remove('basket-pop');void basket.offsetWidth;basket.classList.add('basket-pop');setTimeout(()=>basket.classList.remove('basket-pop'),520)}})}
function addDrinkToCart(id){const c=COCKTAILS.find(x=>x.id===id);if(!c)return;const q=qs('#q-'+id),qty=Math.max(0,Number(q?.textContent||0));if(!qty)return toast('Choose a quantity first');const existing=state.drinkCart.find(x=>x.id===id);if(existing)existing.qty=qty;else state.drinkCart.push({id:c.id,name:c.name,type:c.type,qty});persist();const count=qs('#drinkCartCount');if(count)count.textContent=String(state.drinkCart.reduce((n,x)=>n+x.qty,0));const basket=qs('.drink-basket-btn');if(basket)basket.classList.add('has-items');const card=qs(`[data-cocktail-id="${id}"]`);if(card)card.classList.add('in-order');const btn=card?.querySelector('.add-drink-btn');if(btn){btn.classList.add('added');btn.innerHTML='<span class="order-check">✓</span><span>IN MY ORDER</span>'}animateDrinkToBasket(id)}
function formatOrderTime(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return d.toLocaleString('en-AU',{timeZone:'Asia/Makassar',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).replace(',',' ·').toUpperCase()}
function syncDrinkQuantities(){COCKTAILS.forEach(c=>{const q=qs('#q-'+c.id),item=state.drinkCart.find(x=>x.id===c.id);if(q)q.textContent=String(item?.qty||0);const card=qs(`[data-cocktail-id="${c.id}"]`),btn=card?.querySelector('.add-drink-btn');if(card)card.classList.toggle('in-order',!!item);if(btn){btn.classList.toggle('added',!!item);btn.innerHTML=item?'<span class="order-check">✓</span><span>IN MY ORDER</span>':'Add to order'}});const count=qs('#drinkCartCount');if(count)count.textContent=String(state.drinkCart.reduce((n,x)=>n+x.qty,0));const basket=qs('.drink-basket-btn');if(basket)basket.classList.toggle('has-items',state.drinkCart.length>0)}
function placeDrinkOrder(){if(!state.drinkCart.length)return toast('Your order is empty');const name=state.profile.name||'Guest',items=state.drinkCart.map(x=>({...x})),total=items.reduce((n,x)=>n+x.qty,0);const msg=`🍸 B.B.B COCKTAIL ORDER
Guest: ${name}

`+items.map(x=>`${x.qty} × ${x.name} — ${x.type}`).join('\n')+`

Total drinks: ${total}`;state.drinkOrders.unshift({id:'o'+Date.now(),sentAt:new Date().toISOString(),items});state.drinkCart=[];state.drinkCartOpen=false;persist();renderDrinkCart();syncDrinkQuantities();toast('Order sent to the bar 🍸');window.location.href=`https://wa.me/${CFG.whatsappOrder}?text=${encodeURIComponent(msg)}`}



function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read file'));reader.readAsDataURL(file)})}
async function uploadOneBbbMedia(file){
  const dataUrl=await fileToDataUrl(file);
  await fetch(CFG.mediaUpload,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({file:dataUrl,fileName:file.name||`bbb-media-${Date.now()}`,mimeType:file.type||'application/octet-stream'})});
}
async function handleBbbMediaUpload(files){
  const list=[...(files||[])];if(!list.length)return;
  const btn=qs('#bbbMediaUploadBtn'),status=qs('#bbbMediaStatus');
  const tooLarge=list.find(f=>f.size>20*1024*1024);
  if(tooLarge){toast(`${tooLarge.name} is over 20 MB`);if(status)status.textContent='For now, choose photos or shorter videos under 20 MB each.';return}
  if(btn){btn.disabled=true;btn.textContent=list.length===1?'Uploading…':`Uploading 1 of ${list.length}…`}
  if(status)status.innerHTML='<span class="media-upload-spinner" aria-hidden="true"></span><span>Sending to the B.B.B media roll…</span>';
  try{
    for(let i=0;i<list.length;i++){
      if(btn)btn.textContent=list.length===1?'Uploading…':`Uploading ${i+1} of ${list.length}…`;
      await uploadOneBbbMedia(list[i]);
    }
    if(status)status.innerHTML=`<span class="media-upload-check">✓</span><span>${list.length===1?'Uploaded to the B.B.B media roll':'Media uploaded to the B.B.B media roll'}</span>`;
    toast(list.length===1?'Media uploaded ✓':`${list.length} items uploaded ✓`);
  }catch(err){console.error('BBB media upload failed',err);if(status)status.innerHTML='<span class="media-upload-error">!</span><span>Upload failed. Check your connection and try again.</span>';toast('Upload failed — please try again')}
  finally{if(btn){btn.disabled=false;btn.textContent='Upload media'}}
}

function confirmMassage(){const id=qs('#mtreat')?.value,slot=qs('#mslot')?.value;if(!slot)return toast('Choose a time');if(state.bookings.filter(b=>b.slot===slot&&b.status!=='cancelled').length>=4)return toast('That block is full');const t=MASSAGES.find(x=>x.id===id),bid='b'+Date.now();state.bookings.push({id:bid,slot,treatment:t.name,status:'booked'});state.plans.push({title:t.name,meta:`26 Jan · ${slot} · ${t.mins} min · ${money(t.price)} cash`,pay:'cash',type:'massage',bookingId:bid});persist();navigate('profile');toast('Massage booked')}
function saveCartPlans(){state.cart.forEach(x=>state.plans.push(x));state.cart=[];state.cartOpen=false;persist();renderCart();toast('Saved to My Plans')}
function formatLocal(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function escapeAttr(v=''){return escapeHtml(v)}

function handleClick(e){const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;
 if(a==='nav')navigate(el.dataset.route);
 else if(a==='modal')openModal(el.dataset.modal);
 else if(a==='close-modal')closeModal();
 else if(a==='calendar')addCalendar(el.dataset.title,el.dataset.start,el.dataset.duration);
 else if(a==='photo-upload')qs('#bbb-photo-upload')?.click();
 else if(a==='maps')window.open('https://www.google.com/maps/search/?api=1&query='+el.dataset.query,'_blank');
 else if(a==='near'){const q=el.dataset.query;if(!navigator.geolocation)return window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q+' near Chandra Villas Seminyak'),'_blank');navigator.geolocation.getCurrentPosition(p=>window.open(`https://www.google.com/maps/search/${encodeURIComponent(q)}/@${p.coords.latitude},${p.coords.longitude},15z`,'_blank'),()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q+' near Chandra Villas Seminyak'),'_blank'),{timeout:5000})}
 else if(a==='guide')openModal('guide-'+el.dataset.index);
 else if(a==='drink'){const q=qs('#q-'+el.dataset.id);if(q)q.textContent=String(Math.max(0,Number(q.textContent||0)+Number(el.dataset.delta||0)))}
 else if(a==='order')addDrinkToCart(el.dataset.id);
 else if(a==='drink-cart'){state.drinkClearConfirm=false;state.drinkCartOpen=true;renderDrinkCart()}
 else if(a==='close-drink-cart'){state.drinkClearConfirm=false;state.drinkCartOpen=false;renderDrinkCart()}
 else if(a==='drink-cart-qty'){const i=Number(el.dataset.index),item=state.drinkCart[i];if(item){item.qty=Math.max(0,item.qty+Number(el.dataset.delta||0));if(item.qty===0)state.drinkCart.splice(i,1);persist();renderDrinkCart();syncDrinkQuantities()}}
 else if(a==='remove-drink-cart'){state.drinkCart.splice(Number(el.dataset.index),1);persist();renderDrinkCart();syncDrinkQuantities()}
 else if(a==='place-drink-order')placeDrinkOrder();
 else if(a==='confirm-clear-drink-order'){state.drinkClearConfirm=true;renderDrinkCart()}
 else if(a==='cancel-clear-drink-order'){state.drinkClearConfirm=false;renderDrinkCart()}
 else if(a==='clear-drink-order'){state.drinkCart=[];state.drinkClearConfirm=false;persist();renderDrinkCart();syncDrinkQuantities()}
 else if(a==='rsvp-sunset'){if(!state.plans.some(x=>x.type==='sunset'))state.plans.push({title:'Beanbags, Beers & Sunset',meta:'24 Jan · From 4:00 PM · RSVP',pay:'free',type:'sunset'});persist();closeModal();toast('RSVP saved')}
 else if(a==='save-flight')saveFlight();
 else if(a==='share-flight')shareFlight();
 else if(a==='save-profile')saveProfile();
 else if(a==='slot'){qsa('.slot').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');const input=qs('#mslot');if(input)input.value=el.dataset.slot}
 else if(a==='confirm-massage')confirmMassage();
 else if(a==='add-float'){const f=FLOATS.find(x=>x.id===el.dataset.id);if(f){state.cart.push({id:f.id+'-'+Date.now(),title:f.name,price:f.price,currency:'AUD',type:'float',meta:'26 Jan · 24-hour hire'});persist();toast('Float added to cart')}}
 else if(a==='add-pizza'){const q=Math.max(1,Number(qs('#pizzaqty')?.value||1));state.cart.push({id:'pizza-'+Date.now(),title:`Bali Pizza Party × ${q}`,price:249000*q,currency:'IDR',type:'pizza',meta:'26 Jan · 1:00–3:00 PM'});persist();closeModal();toast('Pizza added to cart')}
 else if(a==='cart'){state.cartOpen=true;renderCart()}
 else if(a==='close-cart'){state.cartOpen=false;renderCart()}
 else if(a==='remove-cart'){state.cart.splice(Number(el.dataset.index),1);persist();renderCart()}
 else if(a==='save-cart')saveCartPlans();
 else if(a==='cancel-plan'){const i=Number(el.dataset.index),p=state.plans[i];if(!p)return;if(p.bookingId){const b=state.bookings.find(x=>x.id===p.bookingId);if(b)b.status='cancelled'}state.plans.splice(i,1);persist();render();toast('Cancelled')}
 else if(a==='swap-fx'){if(!state.fx)return;const aud=qs('#aud'),idr=qs('#idr');const aVal=Number(aud.value||0),iVal=Number(idr.value||0);aud.value=(iVal/state.fx).toFixed(2);idr.value=Math.round(aVal*state.fx)}
}
document.addEventListener('click',handleClick);
document.addEventListener('input',e=>{if(e.target.id==='aud')convertFx('aud');if(e.target.id==='idr')convertFx('idr')});
document.addEventListener('change',e=>{if(e.target.id==='bbb-photo-upload'){const files=[...(e.target.files||[])];if(files.length)handleBbbMediaUpload(files);e.target.value=''}});

window.addEventListener('error',e=>console.error('BBB app error',e.error||e.message));
setInterval(()=>{const c=qs('#countdown');if(c)c.innerHTML=countdown()},1000);
if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{})}
render();
})();
