const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const storage={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const DRIVE_URL='https://drive.google.com/drive/folders/1RYiTM9qjW5V2a5BqU3W_jYM4suv-54Pi';
const VILLA_URL='https://www.chandravillas.com/';
const FLOAT_URL='https://www.getfloatbali.com/';
const PIZZA_URL='https://www.balipizzaparty.com/pizzas';
const ADMIN_EMAIL='shanpendrey@gmail.com';
const APP={route:routeFromHash(),profile:storage.get('bbb_profile',{name:'Shannon',email:'',pin:'',photo:''}),plans:storage.get('bbb_plans',[]),check:storage.get('bbb_check',{}),flights:storage.get('bbb_flights',{toBali:null,home:null}),bookings:storage.get('bbb_bookings',[]),cart:storage.get('bbb_cart',[]),modal:null,fx:null,driverDraft:null};
const CFG={birthday:'2027-01-25T13:00:00+08:00',address:'Jl. Sari Temuku Gg. Sandat, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361, Indonesia',villa:'Chandra Villas · Villa 8',villaPhone:'+62361738091',cocktailWhatsApp:'61432095292',drAri:'628123954567',mobileMedicine:'6281252638533',made:'6281353021044'};
const ITINERARY=[
 ['1:00 PM','Arrive & Settle In','Grab a drink, find your people and settle into the villa. DJ live and cocktails flowing.'],
 ['2:00 PM','The B.B.B Bali Games','The less you know, the better. Teams, competition and plenty of laughs. That’s all you’re getting.'],
 ['2:30 PM','Afternoon Canapés','Little bites. Bali style.'],['4:00 PM','Reset & Recharge','Pool, drinks, showers and a little downtime.'],['5:30 PM','Golden Hour Drinks','Cocktails and pre-dinner grazing as the sun starts to drop.'],['7:00 PM','Dinner','A sit-down buffet feast at the villa.'],['8:00 PM','A Little Something Special…','No spoilers. Just be there.'],['8:30 PM','Drinks, Music & Good Times','The night opens up.'],['11:00 PM','That’s a Wrap','Formal event end — unless you’re still talking.']
];
const COCKTAILS=[
 ['berry','🍓','BERRY BOUJI','Strawberry Daiquiri','Sweet, frozen and considerably more sophisticated than your decisions will be.'],
 ['mint','🌿','MINT CONDITION','Mojito','Fresh, fabulous and holding up remarkably well for fifty.'],
 ['after','☕','AFTER HOURS','Espresso Martini','Because apparently going to bed at a reasonable hour is not on the itinerary.'],
 ['tropic','🍍','TROPIC LIKE IT’S HOT','Piña Colada','Basically a fruit salad with a drinking problem.'],
 ['mini','🍺','MINI BEERS','Licor 43 & Cream','Tiny beer. Big intentions. Absolutely nothing sensible happens after the first one.']
].map(x=>({id:x[0],icon:x[1],name:x[2],type:x[3],desc:x[4]}));
const MASSAGES=[['Balinese Massage',200000,60],['Relaxing Massage',225000,60],['Foot Reflexology',185000,45],['Anti Stress Massage',185000,45],['Deep Tissue Massage',250000,60],['Four Hand Massage',400000,60],['Thai Massage',250000,60],['Natural Coconut Relaxing Massage',250000,60],['Facial Oriflame',185000,60],['Pedicure',185000,60],['Manicure',185000,60],['Creambath',185000,60],['Head + Foot Massage',250000,60],['Pregnancy Massage',200000,60],['Anti Cellulite Massage',350000,60],['Limfatik Drainase',350000,60],['Hair Braid',125000,45]].map((x,i)=>({id:`m${i}`,name:x[0],price:x[1],mins:x[2]}));
const MASSAGE_SLOTS=['10:00 AM','11:30 AM','1:00 PM','2:30 PM','4:00 PM','5:30 PM'];
const PIZZAS={classic:[
 ['Margherita','Tomato sauce, mozzarella, olive oil, fresh basil','🍅'],['Funghi','Mushroom, mozzarella, honey drizzle','🍄'],['Formaggi','Mozzarella, cheddar, parmesan','🧀'],['Capricciosa','Tomato sauce, mozzarella, ham, mushroom, black olives','🫒'],['Diavola','Tomato sauce, mozzarella, salami','🌶️'],['Tropicale','Tomato sauce, ham, mozzarella, pineapple','🍍']
],specialty:[['Specialty selection 1','To be selected with the supplier','⭐'],['Specialty selection 2','To be selected with the supplier','⭐']],dessert:[['Nutella & Fresh Fruit','Nutella with seasonal fresh fruit','🍫']]};
const GUIDE=[
 ['Before You Fly','Passport, insurance, packing, apps and getting organised.'],['Arrival & Airport','What happens from landing to walking out of the terminal.'],['Getting Around','Drivers, Gojek, Grab, Blue Bird and Bali traffic.'],['Money, Shopping & Essentials','Rupiah, ATMs, money changers, supermarkets and pharmacies.'],['Food, Water & Bali Belly','Drinking water, food safety, hydration and what to do if you get sick.'],['Health & Medical','Doctors, pharmacies, hospitals, medication, sun and mosquitoes.'],['Safety & Culture','Local laws, temples, ceremonies, scams and night safety.'],['Staying Longer?','Villa life, wellness, laundry, day trips and longer stays.'],['Bali Hacks','Simple tips that make the trip easier.']
];
const READY=[['passport','Passport checked'],['insurance','Travel insurance'],['visa','Visa / e-VOA'],['levy','Bali Tourist Levy'],['arrival','All Indonesia arrival declaration'],['flight','Arrival + departure flights added']];
function routeFromHash(){return (location.hash.replace(/^#\/?/,'')||'home').split('?')[0]}
function saveState(){storage.set('bbb_profile',APP.profile);storage.set('bbb_plans',APP.plans);storage.set('bbb_check',APP.check);storage.set('bbb_flights',APP.flights);storage.set('bbb_bookings',APP.bookings);storage.set('bbb_cart',APP.cart)}
function money(n,c='IDR'){return c==='AUD'?`$${Number(n).toFixed(2)} AUD`:`Rp${Math.round(Number(n)||0).toLocaleString('id-ID')}`}
function toast(msg){const el=qs('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function go(route){APP.route=route;APP.modal=null;location.hash=`#/${route}`;window.scrollTo({top:0,behavior:'instant'});render()}
window.addEventListener('hashchange',()=>{APP.route=routeFromHash();APP.modal=null;render()});
function headerHtml(){return `<header class="topbar"><div class="brand-mini"><div class="stamp">B.B.B</div><div class="brand-copy"><strong>Nicolle's 50th</strong><span>BALI 2027</span></div></div><button class="btn light" onclick="go('profile')">${esc(APP.profile.name||'My Profile')}</button></header>`}
function navHtml(){const items=[['home','⌂','Home'],['bbb','🎂','B.B.B'],['travel','✈','Travel'],['bali','☀','Bali'],['profile','☺','Me']];return `<nav class="navbar" aria-label="Main navigation">${items.map(x=>`<button class="navitem ${APP.route===x[0]?'active':''}" onclick="go('${x[0]}')"><span class="ico">${x[1]}</span><span>${x[2]}</span></button>`).join('')}</nav>`}
function countdownHtml(){let d=Math.max(0,new Date(CFG.birthday)-new Date());const days=Math.floor(d/864e5);d%=864e5;const hours=Math.floor(d/36e5);d%=36e5;const mins=Math.floor(d/6e4);const secs=Math.floor((d%6e4)/1000);return [[days,'Days'],[hours,'Hours'],[mins,'Mins'],[secs,'Secs']].map(x=>`<div class="count"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
function homePage(){return `<div class="shell">${headerHtml()}<section class="hero"><div class="eyebrow">23–27 January 2027 · Bali</div><h1>Nicolle's<br>50th</h1><div class="bbbline">B.B.B — THE BIG BALI BASH</div><div class="script">Better. Bolder. Boujier.</div><div class="hero-actions"><button class="btn olive" onclick="go('bbb')">Enter the Big Bali Bash</button><button class="btn outline" onclick="go('ready')">Get Bali Ready</button></div><div class="countdown" id="countdown">${countdownHtml()}</div></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">Next up</h2><p class="section-sub">One place for the trip, bookings and reminders.</p></div></div><article class="card"><div class="meta">Sunday 24 January · From 4:00 PM</div><h3>Beanbags, Beers & Sunset</h3><p>The unofficial start to the Bali weekend. Beachside beanbags, sunset drinks and an easy first catch-up.</p><div class="pillrow two"><button class="btn" onclick="openModal('sunset')">View details</button><button class="btn light" onclick="addCalendar('Beanbags, Beers & Sunset','2027-01-24T16:00:00+08:00',180)">Add to calendar</button></div></article></section>
<section class="section"><div class="grid two"><article class="card bbb-home-card bbb-home-feature"><div class="meta">Monday 25 January</div><div class="bbbmark">B.B.B</div><div class="submark">THE BIG BALI BASH</div><div class="script">Better. Bolder. Boujier.</div><p>Nicolle's 50th · Cocktails · Food · Games · Surprises</p><div class="pillrow one"><button class="btn olive" onclick="go('bbb')">ENTER THE B.B.B →</button></div></article><article class="card recovery" style="background:#fff0bd;border:3px solid var(--teal);padding:34px"><div class="meta">Tuesday 26 January</div><h3 style="font-family:Montserrat;color:var(--teal);font-size:42px;font-weight:800;text-transform:uppercase">The Great Aussie Recovery</h3><p>Pizza · Pool · Triple J · Massages · Floaties.<br>Same sun. Less effort.</p><div class="pillrow one"><button class="aus-btn red" onclick="go('recovery')">ENTER THE RECOVERY →</button></div></article></div></section>
<section class="section"><div class="grid two"><article class="card"><div class="meta">Bali Ready</div><h3>Travel wallet & reminders</h3><p>Flights, visa, tourist levy, arrival declaration and your travel checklist in one place.</p><div class="pillrow one"><button class="btn" onclick="go('ready')">Open Bali Ready</button></div></article><article class="card"><div class="meta">The B.B.B Camera Roll</div><h3>Share your photos</h3><p>Add your shots from the trip or browse the group album.</p><div class="camera-actions"><button class="btn olive" onclick="choosePhotos()">Add a photo</button><a class="btn light" href="${DRIVE_URL}" target="_blank" rel="noopener">View photos</a></div></article></div></section></div>${navHtml()}`}
function bbbPage(){return `<div class="shell">${headerHtml()}<section class="bbb-hero"><div class="eyebrow">Nicolle's 50th</div><div class="bbbmark">B.B.B</div><div class="submark">THE BIG BALI BASH</div><div class="script">Better. Bolder. Boujier.</div><div class="eyebrow">Bali 2027</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Monday 25 January</div><h2 class="section-title" style="white-space:nowrap">The Itinerary</h2><p class="section-sub">Here’s how the day unfolds.</p></div><button class="btn light" onclick="addCalendar('Nicolle’s 50th — The Big Bali Bash','2027-01-25T13:00:00+08:00',600)">Add to calendar</button></div><div class="timeline">${ITINERARY.map(x=>`<div class="timeline-row"><div class="time">${x[0]}</div><div><h4>${x[1]}</h4><p>${x[2]}</p></div></div>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Good drinks. Great company.</div><h2 class="section-title">Cocktails</h2><p class="section-sub">Included. Live ordering opens at 1:30 PM on 25 January.</p></div></div><div class="cocktail-grid">${COCKTAILS.map(c=>`<article class="cocktail"><div class="cocktail-art">${c.icon}</div><div class="cocktail-body"><h3>${c.name}</h3><div class="type">${c.type}</div><p>${c.desc}</p><div class="orderbar"><div class="qty"><button onclick="changeDrink('${c.id}',-1)">−</button><b id="qty-${c.id}">0</b><button onclick="changeDrink('${c.id}',1)">+</button></div><button class="btn olive" onclick="orderCocktails()">Add to order</button></div></div></article>`).join('')}</div></section>
<section class="section"><div class="grid two"><article class="card"><div class="meta">2:30 PM</div><h3>Afternoon Canapés</h3><p>Little bites. Bali style.<br><strong>Menu coming soon.</strong></p></article><article class="card"><div class="meta">7:00 PM</div><h3>Tonight's Feast</h3><p>A taste of Bali.<br><strong>Full menu coming soon.</strong></p></article></div></section>
<section class="section"><article class="card"><div class="meta">The B.B.B Playlist</div><h3>Add to the soundtrack</h3><p>Open the shared Spotify playlist and add a song for Bali.</p><div class="pillrow one"><a class="btn olive" href="https://open.spotify.com/s/P6rY4T0" target="_blank" rel="noopener">Open Spotify</a></div></article></section>
<section class="section"><article class="card"><div class="meta">The B.B.B Camera Roll</div><h3>Share your photos</h3><p>Add a photo from your phone, or browse everyone’s uploads.</p><div class="camera-actions"><button class="btn olive" onclick="choosePhotos()">Add a photo</button><a class="btn light" href="${DRIVE_URL}" target="_blank" rel="noopener">View camera roll</a></div></article></section>
<section class="section"><article class="card"><div class="meta">Location</div><h3>${CFG.villa}</h3><p>${CFG.address}</p><div class="pillrow three"><button class="btn" onclick="openMaps('${jsEsc(CFG.address)}')">Open in Maps</button><a class="btn light" href="${VILLA_URL}" target="_blank" rel="noopener">Website</a><a class="btn light" href="tel:${CFG.villaPhone}">Call</a></div></article></section></div>${navHtml()}`}
function travelPage(){const to=APP.flights.toBali,home=APP.flights.home;return `<div class="shell">${headerHtml()}<section class="pagehead"><div class="eyebrow">Your trip</div><h1>Travel</h1><p>Flights, documents and the practical things you need before Bali.</p></section>
<section class="section"><article class="card"><div class="meta">Your flights</div><h3>${to||home?'Flight details saved':'Add your flights'}</h3><p>${to?`<strong>To Bali:</strong> ${esc(to.airline)} ${esc(to.no)} · ${esc(to.from)} → ${esc(to.to)}<br>`:''}${home?`<strong>Home:</strong> ${esc(home.airline)} ${esc(home.no)} · ${esc(home.from)} → ${esc(home.to)}`:'Add both your Bali arrival and flight home so reminders work on both ends.'}</p><div class="pillrow ${to||home?'two':'one'}"><button class="btn" onclick="openModal('flights')">${to||home?'Edit flights':'Add flights'}</button>${to||home?`<button class="btn light" onclick="shareFlights()">Share</button>`:''}</div></article></section>
<section class="section"><article class="card"><div class="meta">Airport pickup</div><h3>Need a driver?</h3><div class="driver-art">${driverSvg()}</div><p>Made offers guaranteed airport pickup with a personalised sign and clear communication. Kuta/Legian $30 AUD · Seminyak $40 AUD. Add arrival drinks if you want them waiting.</p><div class="pillrow one"><button class="btn olive" onclick="openModal('driver')">Book airport pickup</button></div></article></section>
<section class="section"><article class="card"><div class="meta">Bali Ready</div><h3>Checklist & documents</h3><p>Visa, levy, arrival declaration, insurance, passport and flight details.</p><div class="pillrow one"><button class="btn olive" onclick="go('ready')">Open Bali Ready</button></div></article></section>
<section class="section"><article class="card"><div class="meta">Your Bali base</div><h3>Chandra Villas</h3><p>Private villas in Seminyak with personalised service, pools and easy access to the beach, dining and shopping.</p><p>${CFG.address}</p><div class="pillrow three"><button class="btn" onclick="openMaps('${jsEsc(CFG.address)}')">Open in Maps</button><a class="btn light" href="${VILLA_URL}" target="_blank" rel="noopener">Website</a><a class="btn light" href="tel:${CFG.villaPhone}">Call</a></div></article></section></div>${navHtml()}`}
function readyPage(){const done=READY.filter(x=>APP.check[x[0]]).length;const pct=Math.round(done/READY.length*100);return `<div class="shell">${headerHtml()}<section class="pagehead"><div class="eyebrow">Bali Ready</div><h1>Ready to go?</h1><p>Keep the important travel jobs clear and easy to check off.</p></section><article class="card"><div class="meta">Your progress</div><h3>${pct}% ready</h3><div style="height:10px;background:#eee4d5;border-radius:99px;overflow:hidden;margin:14px 0 8px"><div style="height:100%;width:${pct}%;background:var(--olive)"></div></div><p>${pct===100?'You’re Bali ready 🌴':'Tick things off as you organise them.'}</p></article>
<section class="section"><div class="grid two">${READY.map(x=>`<label class="card" style="display:flex;gap:14px;align-items:center;cursor:pointer"><input type="checkbox" ${APP.check[x[0]]?'checked':''} onchange="toggleReady('${x[0]}',this.checked)" style="width:22px;height:22px;accent-color:var(--olive)"><div><div class="meta">${APP.check[x[0]]?'Complete':'To do'}</div><h3 style="font-size:26px;margin-bottom:0">${x[1]}</h3></div></label>`).join('')}</div></section>
<section class="section"><article class="card"><div class="meta">1 · Visa / e-VOA</div><h3>Visa / e-VOA</h3><p>Use the official immigration site. Keep your approved visa accessible on your phone.</p><div class="video-actions"><a class="btn olive" target="_blank" rel="noopener" href="https://evisa.imigrasi.go.id/">Official site</a><button class="btn light" onclick="openModal('visaHow')">How to apply</button><a class="btn light" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=Indonesia+eVOA+how+to+apply+official">Watch video ▶</a></div></article></section>
<section class="section"><article class="card"><div class="meta">2 · Tourist levy</div><h3>Bali Tourist Levy</h3><p>Complete the Bali levy before travel and keep the QR code on your phone.</p><div class="video-actions"><a class="btn olive" target="_blank" rel="noopener" href="https://lovebali.baliprov.go.id/">Official site</a><button class="btn light" onclick="openModal('levyHow')">How to apply</button><a class="btn light" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=Love+Bali+tourist+levy+how+to+pay">Watch video ▶</a></div></article></section>
<section class="section"><article class="card"><div class="meta">3 · Arrival declaration</div><h3>All Indonesia</h3><p>Complete the official arrival declaration within the required window before arrival and keep the QR code accessible.</p><div class="video-actions"><a class="btn olive" target="_blank" rel="noopener" href="https://allindonesia.imigrasi.go.id/">Official site</a><button class="btn light" onclick="openModal('arrivalHow')">How to complete</button><a class="btn light" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=All+Indonesia+arrival+declaration+how+to">Watch video ▶</a></div></article></section>
<section class="section"><article class="card"><div class="meta">Airport pickup</div><h3>Arrive without the scramble</h3><p>Book Made for airport pickup and optionally have drinks waiting.</p><div class="pillrow one"><button class="btn" onclick="openModal('driver')">Book Made</button></div></article></section></div>${navHtml()}`}
function baliPage(){return `<div class="shell">${headerHtml()}<section class="pagehead"><div class="eyebrow">Useful in Bali</div><h1>Bali Basics</h1><p>Useful information, contacts and practical shortcuts when you need them.</p></section>
<article class="card weather" id="weather"><div class="meta">Live Seminyak weather</div><h3>Loading weather…</h3></article>
<section class="section"><article class="card"><div class="meta">Live currency</div><h3>AUD ↔ IDR</h3><div id="fxrate" class="fx-rate">Loading live rate…</div><div class="converter"><div class="field"><label>Australian dollars</label><div class="money-input"><input id="aud" type="number" value="10" oninput="convertCurrency('aud')"><span>AUD</span></div></div><button class="swap" onclick="swapCurrency()">↕</button><div class="field"><label>Indonesian rupiah</label><div class="money-input"><input id="idr" type="number" oninput="convertCurrency('idr')"><span>IDR</span></div></div></div><p id="fxnote">Live indicative rate. Banks, cards and money changers may differ.</p><div id="fxupdated" class="fx-updated"></div></article></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">Quick help</h2><p class="section-sub">Useful contacts when you need them.</p></div></div><div class="help-grid"><article class="card help-card"><div><div class="meta">Medical</div><h3>Dr Ari</h3><p>Medical assistance via WhatsApp.</p></div><a class="btn" href="https://wa.me/${CFG.drAri}" target="_blank" rel="noopener">WhatsApp Dr Ari</a></article><article class="card help-card"><div><div class="meta">Medical clinic</div><h3>Mobile Medicine</h3><p>Medical clinic via WhatsApp.</p></div><a class="btn" href="https://wa.me/${CFG.mobileMedicine}" target="_blank" rel="noopener">WhatsApp clinic</a></article><article class="card help-card"><div><div class="meta">Laundry</div><h3>Laundry Delivery</h3><p>Laundry Bali Express pickup and delivery service.</p></div><a class="btn" href="https://www.laundrybaliexpress.com/" target="_blank" rel="noopener">Open service</a></article><article class="card help-card"><div><div class="meta">Money</div><h3>Travel card options</h3><p>Wise and Revolut are available for managing travel spending.</p></div><button class="btn" onclick="openModal('cards')">View options</button></article></div></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">Find near me</h2><p class="section-sub">Open a nearby search in Maps.</p></div></div><div class="findgrid">${['Pharmacy','ATM','Convenience store','Supermarket','Medical clinic','Hospital','Money changer','Coffee','Food','Beach','Petrol station'].map(x=>`<button class="find-btn" onclick="findNear('${x}')">${x}<small>Search nearby →</small></button>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">The Bali Guide</h2><p class="section-sub">Short cards here; full useful guides inside.</p></div></div><div class="guide-grid">${GUIDE.map((x,i)=>`<button class="guide-btn" onclick="go('guide-${i}')">${x[0]}<small>${x[1]}</small></button>`).join('')}</div></section></div>${navHtml()}`}
function guidePage(index){const g=GUIDE[index]||GUIDE[0];const content=guideContent(index);return `<div class="shell page-route">${headerHtml()}<section class="pagehead"><div class="eyebrow">The Bali Guide</div><h1>${g[0]}</h1><p>${g[1]}</p></section><article class="card guide-content">${content}</article><section class="section"><button class="btn light" onclick="go('bali')">← Back to Bali Guide</button></section></div>${navHtml()}`}
function guideContent(i){const blocks=[
`<h3>Passport & documents</h3><ul><li>Check passport validity and keep clear digital copies of important documents.</li><li>Keep travel insurance details, flight confirmations and accommodation information easy to access offline.</li><li>Pack a pen in your carry-on and save emergency contacts in your phone.</li></ul><h3>Before departure</h3><ul><li>Complete the visa/e-VOA, Bali Tourist Levy and All Indonesia declaration using the official links in Bali Ready.</li><li>Consider an eSIM or roaming plan before you land.</li><li>Bring a universal adaptor, sunscreen, lightweight clothing and any regular medication in original packaging.</li></ul>`,
`<h3>Landing in Bali</h3><ul><li>Follow airport signage for immigration or e-gates, baggage collection and customs.</li><li>Keep entry QR codes and your passport ready rather than buried in your luggage.</li><li>Once outside, use your booked driver or an official transport option.</li></ul><h3>Pickup</h3><ul><li>If you booked Made through the app, check My Plans for your pickup details and total cash due.</li><li>Allow extra time during busy arrival periods.</li></ul>`,
`<h3>Cars & bikes</h3><ul><li>Grab, Gojek, Blue Bird taxis and private drivers are common options.</li><li>Bali traffic can make short distances take much longer than expected, especially around Seminyak and Canggu.</li><li>Use a reputable transport provider and confirm the destination before leaving.</li></ul><h3>Walking</h3><ul><li>Footpaths can be uneven. Take care around traffic, driveways and scooters.</li></ul>`,
`<h3>Cash & cards</h3><ul><li>Rupiah is the local currency. Keep some small notes for cash-only purchases and tips.</li><li>Use reputable or bank-attached ATMs and established money changers.</li><li>Wise and Revolut are linked in Quick Help if you want travel-card options.</li></ul><h3>Shopping</h3><ul><li>Keep receipts for higher-value purchases.</li><li>Check your home-country customs allowances before flying home.</li></ul>`,
`<h3>Water & hydration</h3><ul><li>Do not drink tap water. Use sealed bottled or properly filtered water.</li><li>Hydrate more than you think you need to, especially after alcohol, sun or pool time.</li><li>Electrolytes are useful to keep on hand.</li></ul><h3>If you feel unwell</h3><ul><li>Rest, hydrate and keep food simple.</li><li>Seek medical help for severe pain, persistent vomiting, blood, high fever, dehydration or symptoms that are not improving.</li><li>Dr Ari and Mobile Medicine are linked in Quick Help.</li></ul>`,
`<h3>Medical help</h3><ul><li>Use Dr Ari or Mobile Medicine from Quick Help when you need local medical support.</li><li>Keep your travel insurance policy and emergency-assistance number saved offline.</li></ul><h3>Sun, heat & mosquitoes</h3><ul><li>Use sunscreen, seek shade, drink water and take breaks from the heat.</li><li>Use mosquito repellent, particularly around dusk and in garden areas.</li></ul>`,
`<h3>Respectful travel</h3><ul><li>Indonesian law applies while you are in Bali.</li><li>Dress and behave respectfully around temples, ceremonies and offerings.</li><li>Do not touch or step on offerings placed on the ground.</li></ul><h3>Personal safety</h3><ul><li>Use reputable transport at night and keep an eye on phones and bags in busy areas.</li><li>Be cautious with unfamiliar ATMs, unofficial money changers and unusually good deals.</li></ul>`,
`<h3>Longer stays</h3><ul><li>Choose your area based on how you actually want to spend your days, because traffic can shape the experience.</li><li>Ask your villa about housekeeping, laundry, transport and local recommendations.</li><li>Book popular restaurants, wellness appointments and day trips ahead during busy periods.</li></ul>`,
`<h3>Easy wins</h3><ul><li>Keep WhatsApp installed — many Bali businesses use it for bookings and updates.</li><li>Screenshot addresses and confirmations before leaving Wi-Fi.</li><li>Keep a power bank, electrolytes and a small amount of cash in your day bag.</li><li>Use laundry pickup rather than spending holiday time washing clothes.</li></ul>`
];return blocks[i]||blocks[0]}
function profilePage(){return `<div class="shell">${headerHtml()}<section class="pagehead"><div class="eyebrow">Your space</div><h1>My Profile</h1><p>Your profile, bookings and trip plans.</p></section><article class="card profile-card"><div class="avatar">${APP.profile.photo?`<img src="${APP.profile.photo}" alt="Profile photo" style="width:100%;height:100%;object-fit:cover">`:'☺'}</div><div><h3>${esc(APP.profile.name||'Guest')}</h3><p>${APP.profile.email?esc(APP.profile.email):'Add your email for confirmations and receipts.'}</p></div></article>
<section class="section"><article class="card"><div class="form"><div class="field"><label>Name</label><input id="profileName" value="${attr(APP.profile.name||'')}"></div><div class="field"><label>Email address</label><input id="profileEmail" type="email" value="${attr(APP.profile.email||'')}" placeholder="you@example.com"></div><div class="field"><label>4-digit PIN</label><input id="profilePin" inputmode="numeric" maxlength="4" value="${attr(APP.profile.pin||'')}" placeholder="1234"></div><div class="field"><label>Profile photo</label><button class="btn light" onclick="chooseProfilePhoto()">Add / change photo</button><input id="profilePhoto" type="file" accept="image/*" hidden></div><button class="btn full" onclick="saveProfile()">Save profile</button></div></article></section>
<section class="section"><div class="section-head"><div><h2 class="section-title">My Plans</h2><p class="section-sub">Everything you’ve RSVP’d, booked or purchased.</p></div></div>${APP.plans.length?APP.plans.map((p,i)=>`<article class="card plan" style="margin-bottom:12px"><div><span class="status-badge">${planStatus(p)}</span><h3>${esc(p.title)}</h3><p>${esc(p.meta||'')}</p>${p.total?`<strong>${esc(p.total)}</strong>`:''}</div><div class="actions"><button class="btn light" onclick="cancelPlan(${i})">Cancel</button></div></article>`).join(''):`<article class="card"><p>Nothing booked yet.</p></article>`}</section></div>${navHtml()}`}
function recoveryPage(){return `<div class="recovery-shell"><div class="shell"><div class="recovery-top"><button class="aus-btn" onclick="go('home')">← Back</button><button class="aus-btn red" onclick="openPizzaCart()">Pizza cart (${APP.cart.length})</button></div><section class="recovery-hero"><div class="recovery-brandlock"><div class="recovery-kicker">Australia Day · 26 January 2027 · Bali</div><div class="recovery-title">The Great<br>Aussie<br>Recovery</div><div class="recovery-tag">SAME SUN. LESS EFFORT.</div><div class="recovery-doodles"><span>☀️</span><span>🍕</span><span>〰️</span><span>🌴</span><span>🛟</span></div><p>Pizza · Pool · Triple J · Massages · Floaties</p></div></section>
<section class="section"><article class="card recovery-card"><div class="meta">Tuesday 26 January · From 10:00 AM</div><h3>The morning after the Big Bali Bash…</h3><p>Yesterday was the party. Today is pizza, pool, Triple J, massages and absolutely no pressure to do anything.</p><div class="pillrow three"><button class="aus-btn" onclick="openModal('recoveryItinerary')">Itinerary</button><a class="aus-btn yellow" href="https://www.abc.net.au/triplej/live/triplej" target="_blank" rel="noopener">Triple J</a><button class="aus-btn yellow" onclick="addCalendar('The Great Aussie Recovery','2027-01-26T10:00:00+08:00',600)">Calendar</button></div></article></section>
<section class="section"><div class="grid two"><article class="card recovery-card"><div class="meta">1:00–3:00 PM</div><h3>🍕 Bali Pizza Party</h3><p>Fresh pizza served at the villa as part of The Great Aussie Recovery.</p><div class="pillrow one"><button class="aus-btn red" onclick="openModal('pizzaInfo')">See details</button></div></article><article class="card recovery-card"><div class="meta">From 10:00 AM</div><h3>💆 Massage & Spa</h3><p>Choose your treatment and time. Four appointments are available in each 90-minute block.</p><div class="pillrow one"><button class="aus-btn" onclick="openModal('massage')">Book massage</button></div></article><article class="card recovery-card"><div class="meta">Pool day</div><h3>🛟 Float Hire</h3><p>Browse the supplier options, then book directly with Get Float Bali.</p><div class="pillrow one"><button class="aus-btn yellow" onclick="go('floats')">Choose your float</button></div></article></div></section></div></div>${navHtml()}`}
function pizzaMenuPage(){const section=(label,arr)=>`<div class="section"><div class="pizza-category">${label}</div><div class="pizza-grid">${arr.map(p=>`<article class="pizza-card"><div class="pizza-illustration">${p[2]}</div><div class="pizza-card-body"><h3>${p[0]}</h3><p>${p[1]}</p></div></article>`).join('')}</div></div>`;return `<div class="recovery-shell"><div class="shell"><button class="aus-btn" onclick="go('recovery')">← Back to Recovery</button><section class="pagehead" style="margin-top:20px;background:#fff6d8;border:2px solid var(--teal)"><div class="recovery-kicker">Bali Pizza Party</div><h1 style="color:var(--teal)">The Menu</h1><p>Here’s what’s firing up at the villa. This is included in the package — no menu pricing or add-to-cart buttons here.</p></section>${section('6 Classic Pizzas',PIZZAS.classic)}${section('2 Specialty Pizzas',PIZZAS.specialty)}${section('Something Sweet',PIZZAS.dessert)}<section class="section"><article class="card recovery-card"><h3>Good pizza · Good tunes · Good company</h3><p>The specialty selections will update here once they’re locked with the supplier.</p><div class="pillrow one"><button class="aus-btn" onclick="go('recovery')">← Back to Recovery</button></div></article></section></div></div>${navHtml()}`}
function floatsPage(){return `<div class="recovery-shell"><div class="shell"><button class="aus-btn" onclick="go('recovery')">← Back to Recovery</button><section class="pagehead" style="margin-top:20px;background:#fff6d8;border:2px solid var(--teal)"><div class="recovery-kicker">The Great Aussie Recovery</div><h1 style="color:var(--teal)">Choose Your Float</h1><p>Browse Get Float Bali’s range, then book directly with the supplier. No app cart or payment needed.</p></section><article class="card recovery-card"><h3>See the full current range</h3><p>The supplier catalogue changes, so the app sends you to Get Float Bali for the complete live selection, availability and booking.</p><div class="pillrow two"><a class="aus-btn yellow" href="${FLOAT_URL}" target="_blank" rel="noopener">Browse floaties</a><a class="aus-btn" href="https://wa.me/6282115157799" target="_blank" rel="noopener">WhatsApp supplier</a></div></article></div></div>${navHtml()}`}
function openModal(name){APP.modal=name;renderModal()}
function closeModal(){APP.modal=null;renderModal()}
function renderModal(){qsa('.overlay,.modal').forEach(el=>el.remove());if(!APP.modal)return;document.body.insertAdjacentHTML('beforeend','<div class="overlay" onclick="closeModal()"></div><div class="modal" role="dialog" aria-modal="true"><div class="modal-card" id="modalCard"></div></div>');const m=qs('#modalCard');if(!m)return;
  if(APP.modal==='sunset')m.innerHTML=`<div class="eyebrow">Sunday 24 January · From 4:00 PM</div><h2>Beanbags, Beers & Sunset</h2><p>The unofficial start to the Bali weekend. We’ll organise beachside beanbags, sunset drinks and an easy first catch-up. Totally optional — come for one drink or stay for sunset.</p><div class="pillrow three"><button class="btn olive" onclick="rsvpSunset()">I’m in</button><button class="btn light" onclick="addCalendar('Beanbags, Beers & Sunset','2027-01-24T16:00:00+08:00',180)">Add to calendar</button><button class="btn light" onclick="closeModal()">Close</button></div>`;
  if(APP.modal==='flights')m.innerHTML=flightFormHtml();
  if(APP.modal==='driver')m.innerHTML=driverFormHtml();
  if(APP.modal==='pizzaInfo')m.innerHTML=`<div class="eyebrow">Tuesday 26 January · 1:00–3:00 PM</div><h2>Bali Pizza Party 🍕</h2><p>Fresh pizza served at the villa as part of The Great Aussie Recovery.</p><div class="card" style="box-shadow:none;margin-top:18px"><div class="meta">What’s included</div><p>6 classic pizzas · 2 specialty pizzas · Nutella & fresh fruit dessert pizza.</p></div><div class="pillrow two"><button class="aus-btn red" onclick="closeModal();go('pizza-menu')">View the menu →</button><button class="aus-btn" onclick="openModal('pizzaBooking')">Book / pay</button></div><div class="pillrow one"><button class="aus-btn yellow" onclick="closeModal()">Back</button></div>`;
  if(APP.modal==='pizzaBooking')m.innerHTML=`<div class="eyebrow">Bali Pizza Party</div><h2>Book your spot</h2><p>Rp249,000 per person. This is the only item paid through Stripe in the app.</p><div class="field"><label>People</label><input id="pizzaQty" type="number" min="1" max="20" value="1"></div><div class="pillrow two"><button class="aus-btn red" onclick="addPizzaToCart()">Add to cart</button><button class="aus-btn" onclick="openModal('pizzaInfo')">Back</button></div>`;
  if(APP.modal==='massage'){m.classList.add('wide');m.innerHTML=massageHtml()}
  if(APP.modal==='recoveryItinerary')m.innerHTML=recoveryItineraryHtml();
  if(APP.modal==='cards')m.innerHTML=`<div class="eyebrow">Money in Bali</div><h2>Travel card options</h2><div class="grid two"><article class="card"><h3>Wise</h3><p>Multi-currency travel card and app.</p><a class="btn" target="_blank" rel="noopener" href="https://wise.com/au/travel-money/travel-money-card">Visit Wise</a></article><article class="card"><h3>Revolut</h3><p>Travel card and app for managing currencies.</p><a class="btn" target="_blank" rel="noopener" href="https://www.revolut.com/en-AU/travel/travel-money-card/">Visit Revolut</a></article></div><div class="pillrow one"><button class="btn light" onclick="closeModal()">Close</button></div>`;
  if(APP.modal==='visaHow')m.innerHTML=howToHtml('Visa / e-VOA',[['1. Choose the correct visa','For a short tourist stay, select the appropriate visitor visa for your circumstances on the official site.'],['2. Prepare your documents','Have your passport data page, photo and onward/return travel details ready where requested.'],['3. Enter details carefully','Check your name, passport number, dates and Indonesian address before submitting.'],['4. Pay and save your visa','After approval, keep a digital copy accessible on your phone.']]);
  if(APP.modal==='levyHow')m.innerHTML=howToHtml('Bali Tourist Levy',[['1. Open Love Bali','Use the official Love Bali website or app.'],['2. Enter your details','Provide the requested passport, name, email and arrival information.'],['3. Pay the levy','Complete payment through the official checkout.'],['4. Save the voucher','Keep the emailed voucher / QR code available for checkpoints.']]);
  if(APP.modal==='arrivalHow')m.innerHTML=howToHtml('All Indonesia',[['1. Open the official site','Use the official All Indonesia declaration site.'],['2. Complete traveller details','Enter the requested arrival, passport and declaration information carefully.'],['3. Submit in the permitted window','Complete it within the timeframe stated by the official service.'],['4. Save the QR code','Keep the confirmation accessible for arrival.']]);
}
function flightFormHtml(){const a=APP.flights.toBali||{},h=APP.flights.home||{};return `<div class="eyebrow">Your flights</div><h2>Arrival & departure</h2><div class="form"><h3 style="font-size:28px">Flight to Bali</h3>${flightFields('to',a,'PER','DPS')}<h3 style="font-size:28px;margin-top:10px">Flight home</h3>${flightFields('home',h,'DPS','PER')}<div class="pillrow two"><button class="btn olive" onclick="saveFlights()">Save flights</button><button class="btn light" onclick="closeModal()">Cancel</button></div></div>`}
function flightFields(prefix,f,fromDefault,toDefault){return `<div class="field"><label>Airline</label><input id="${prefix}Airline" value="${attr(f.airline||'')}" placeholder="Jetstar"></div><div class="field"><label>Flight number</label><input id="${prefix}No" value="${attr(f.no||'')}" placeholder="JQ116"></div><div class="grid two"><div class="field"><label>From</label><input id="${prefix}From" value="${attr(f.from||fromDefault)}"></div><div class="field"><label>To</label><input id="${prefix}To" value="${attr(f.to||toDefault)}"></div></div><div class="grid two"><div class="field"><label>Departure</label><input id="${prefix}Depart" type="datetime-local" value="${attr(f.depart||'')}"></div><div class="field"><label>Arrival</label><input id="${prefix}Arrive" type="datetime-local" value="${attr(f.arrive||'')}"></div></div>`}
function driverFormHtml(){const f=APP.flights.toBali||{};return `<div class="eyebrow">Airport pickup</div><h2>Book Made</h2><div class="driver-art">${driverSvg()}</div><p>Guaranteed pickup · Personalised sign · Great communication</p><div class="form"><div class="field"><label>Drop-off area</label><select id="driverArea" onchange="updateDriverTotal()"><option value="30">Kuta / Legian — $30 AUD</option><option value="40" selected>Seminyak — $40 AUD</option></select></div><div class="field"><label>Arrival flight</label><input id="driverFlight" value="${attr(f.airline&&f.no?`${f.airline} ${f.no}`:'')}" placeholder="Jetstar JQ..."></div><div class="field"><label>Arrival date & time</label><input id="driverArrival" type="datetime-local" value="${attr(f.arrive||'')}"></div><div class="field"><label>Personalised sign name</label><input id="driverSign" value="${attr(APP.profile.name||'')}" placeholder="Shannon"></div><div class="meta" style="margin-top:8px">Drinks waiting on arrival?</div><div class="drink-order">${drinkRow('Bintang',3,'bintang')}${drinkRow('Bintang Crystal',3,'crystal')}${drinkRow('Smirnoff Ice Lemon',4,'lemon')}${drinkRow('Smirnoff Ice Raspberry',4,'raspberry')}</div><div class="total-box"><span>Total due in cash</span><br><strong id="driverTotal">$40.00 AUD</strong><p style="margin:4px 0 0">Cash on delivery.</p></div><div class="pillrow two"><button class="btn olive" onclick="confirmDriver()">Confirm booking</button><button class="btn light" onclick="closeModal()">Cancel</button></div></div>`}
function drinkRow(name,price,id){return `<div><strong>${name}</strong><br><small>$${price}.00 AUD each</small></div><div class="qty"><button onclick="changeArrivalDrink('${id}',-1)">−</button><b id="driver-${id}">0</b><button onclick="changeArrivalDrink('${id}',1)">+</button></div>`}
function massageHtml(){return `<div class="eyebrow">The Great Aussie Recovery</div><h2>Book Massage</h2><p>Four appointments are available in each 90-minute block, from 10:00 AM through 5:30 PM. Payment is cash on the day.</p><div class="field"><label>Treatment</label><select id="massageTreatment">${MASSAGES.map(x=>`<option value="${x.id}">${x.name} · ${x.mins} min · ${money(x.price)}</option>`).join('')}</select></div><div class="field"><label>Time block</label><input id="massageSlot" type="hidden"><div class="slotgrid">${MASSAGE_SLOTS.map(s=>{const used=APP.bookings.filter(b=>b.slot===s&&b.status!=='cancelled').length;return `<button class="slot" onclick="selectMassageSlot(this,'${s}')"><b>${s}</b><span>${Math.max(0,4-used)} spots left</span></button>`}).join('')}</div></div><div class="pillrow two"><button class="aus-btn" onclick="confirmMassage()">Confirm · cash on day</button><button class="aus-btn yellow" onclick="closeModal()">Cancel</button></div>`}
function recoveryItineraryHtml(){const rows=[['10:00 AM','Massage & Spa Bookings Commence'],['11:00 AM','The Great Aussie Recovery Begins'],['11:00 AM','1:00 PM','Pool, Music, Drinks & Chill'],['1:00 PM','Bali Pizza Party Begins'],['1:00 PM','3:00 PM','Pizza Party'],['3:00 PM','Pizza Party Finishes'],['3:00 PM','4:00 PM','Pool, Triple J & Recovery Mode'],['4:00 PM','No Schedule']];return `<div class="eyebrow">Tuesday 26 January 2027</div><h2>The Itinerary</h2><div class="timeline recovery-itinerary">${rows.map(r=>{if(r.length===3)return `<div class="timeline-row"><div class="time range-time"><span>${r[0]}</span><small>to</small><span>${r[1]}</span></div><div><h4>${r[2]}</h4></div></div>`;return `<div class="timeline-row"><div class="time">${r[0]}</div><div><h4>${r[1]}</h4></div></div>`}).join('')}</div><div class="pillrow one"><button class="aus-btn" onclick="closeModal()">Close</button></div>`}
function howToHtml(title,steps){return `<div class="eyebrow">${title}</div><h2>How to apply</h2>${steps.map(s=>`<div class="card" style="box-shadow:none;margin-top:14px"><strong>${s[0]}</strong><p>${s[1]}</p></div>`).join('')}<div class="pillrow one"><button class="btn light" onclick="closeModal()">Close</button></div>`}
function changeDrink(id,delta){const el=qs(`#qty-${id}`);if(!el)return;el.textContent=String(Math.max(0,Number(el.textContent||0)+delta))}
function orderCocktails(){const items=COCKTAILS.map(c=>({c,qty:Number(qs(`#qty-${c.id}`)?.textContent||0)})).filter(x=>x.qty>0);if(!items.length)return toast('Choose a drink first');if(new Date()<new Date('2027-01-25T13:30:00+08:00'))return toast('Orders open at 1:30 PM on 25 Jan');const msg=`${APP.profile.name||'Guest'} has ordered ${items.map(x=>`${x.qty} x ${x.c.name}`).join(', ')}`;window.open(`https://wa.me/${CFG.cocktailWhatsApp}?text=${encodeURIComponent(msg)}`,'_blank')}
function rsvpSunset(){if(!APP.plans.some(p=>p.type==='sunset'))APP.plans.push({type:'sunset',title:'Beanbags, Beers & Sunset',meta:'24 Jan · From 4:00 PM',status:'Confirmed'});saveState();closeModal();toast('RSVP saved')}
function toggleReady(key,val){APP.check[key]=val;saveState();render()}
function choosePhotos(){const picker=qs('#photoPicker');if(!picker)return;picker.value='';picker.onchange=()=>{if(!picker.files.length)return;toast(`${picker.files.length} photo${picker.files.length===1?'':'s'} selected — opening Drive`);setTimeout(()=>window.open(DRIVE_URL,'_blank'),650)};picker.click()}
function chooseProfilePhoto(){const input=qs('#profilePhoto');if(!input)return;input.onchange=()=>toast(input.files?.length?'Photo ready — tap Save profile':'');input.click()}
function saveProfile(){const name=qs('#profileName')?.value.trim()||'';const email=qs('#profileEmail')?.value.trim()||'';const pin=qs('#profilePin')?.value.trim()||'';if(!name)return toast('Add your name');if(email&&!/^\S+@\S+\.\S+$/.test(email))return toast('Check your email address');if(pin&&!/^\d{4}$/.test(pin))return toast('PIN must be 4 digits');const input=qs('#profilePhoto');const file=input?.files?.[0];const done=photo=>{APP.profile={...APP.profile,name,email,pin,photo:photo||APP.profile.photo||''};saveState();render();toast('Profile saved')};if(!file)return done();const reader=new FileReader();reader.onload=()=>done(reader.result);reader.readAsDataURL(file)}
function planStatus(p){if(p.status)return p.status;if(p.pay==='cash')return 'Cash on day';if(p.pay==='paid')return 'Paid';return 'Confirmed'}
function cancelPlan(i){if(!confirm('Cancel this plan?'))return;const p=APP.plans[i];if(p?.bookingId){const b=APP.bookings.find(x=>x.id===p.bookingId);if(b)b.status='cancelled'}APP.plans.splice(i,1);saveState();render();toast('Cancelled')}
function saveFlights(){const read=prefix=>({airline:qs(`#${prefix}Airline`)?.value.trim()||'',no:qs(`#${prefix}No`)?.value.trim()||'',from:qs(`#${prefix}From`)?.value.trim().toUpperCase()||'',to:qs(`#${prefix}To`)?.value.trim().toUpperCase()||'',depart:qs(`#${prefix}Depart`)?.value||'',arrive:qs(`#${prefix}Arrive`)?.value||''});const to=read('to'),home=read('home');if(Object.values(to).some(v=>!v)||Object.values(home).some(v=>!v))return toast('Complete both flights');APP.flights={toBali:to,home};APP.check.flight=true;saveState();closeModal();render();toast('Flights saved')}
async function shareFlights(){const a=APP.flights.toBali,h=APP.flights.home;const text=[`${APP.profile.name||'Guest'}'s Bali flights ✈️`,a?`TO BALI: ${a.airline} ${a.no} · ${a.from} → ${a.to} · ${formatDateTime(a.depart)}`:'',h?`HOME: ${h.airline} ${h.no} · ${h.from} → ${h.to} · ${formatDateTime(h.depart)}`:''].filter(Boolean).join('\n');if(navigator.share){try{await navigator.share({title:'My Bali flights',text});return}catch{}}copyText(text)}
function changeArrivalDrink(id,delta){const el=qs(`#driver-${id}`);if(!el)return;el.textContent=String(Math.max(0,Number(el.textContent||0)+delta));updateDriverTotal()}
function driverBreakdown(){const area=Number(qs('#driverArea')?.value||40);const qty=id=>Number(qs(`#driver-${id}`)?.textContent||0);const drinks=[['Bintang',qty('bintang'),3],['Bintang Crystal',qty('crystal'),3],['Smirnoff Ice Lemon',qty('lemon'),4],['Smirnoff Ice Raspberry',qty('raspberry'),4]].filter(x=>x[1]>0);const drinkTotal=drinks.reduce((a,x)=>a+x[1]*x[2],0);return{area,drinks,total:area+drinkTotal}}
function updateDriverTotal(){const b=driverBreakdown();const el=qs('#driverTotal');if(el)el.textContent=money(b.total,'AUD')}
async function confirmDriver(){if(!APP.profile.email)return toast('Add your email in My Profile first');const flight=qs('#driverFlight')?.value.trim()||'';const arrival=qs('#driverArrival')?.value||'';const sign=qs('#driverSign')?.value.trim()||APP.profile.name||'Guest';if(!flight||!arrival)return toast('Add flight and arrival time');const b=driverBreakdown();const area=b.area===30?'Kuta / Legian':'Seminyak';const id=`driver-${Date.now()}`;const drinkText=b.drinks.length?b.drinks.map(x=>`${x[1]} x ${x[0]}`).join(', '):'No arrival drinks';const plan={id,type:'driver',title:`Airport pickup with Made`,meta:`${formatDateTime(arrival)} · ${area} · ${flight} · ${drinkText}`,status:'Cash on delivery',total:money(b.total,'AUD')};APP.plans.push(plan);saveState();const ok=await notifyAdmin('driver',{guest:APP.profile.name,email:APP.profile.email,flight,arrival,area,sign,drinks:drinkText,total:money(b.total,'AUD'),made:'+62 813-5302-1044'});closeModal();render();toast(ok?'Pickup saved · admin emailed':'Pickup saved · email service needs setup')}
function selectMassageSlot(btn,slot){qsa('.slot').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const hidden=qs('#massageSlot');if(hidden)hidden.value=slot}
async function confirmMassage(){if(!APP.profile.email)return toast('Add your email in My Profile first');const id=qs('#massageTreatment')?.value;const slot=qs('#massageSlot')?.value;if(!slot)return toast('Choose a time');const used=APP.bookings.filter(b=>b.slot===slot&&b.status!=='cancelled').length;if(used>=4)return toast('That block is full');const t=MASSAGES.find(x=>x.id===id);if(!t)return toast('Choose a treatment');const bookingId=`massage-${Date.now()}`;APP.bookings.push({id:bookingId,slot,treatment:t.name,status:'booked'});APP.plans.push({bookingId,type:'massage',title:t.name,meta:`26 Jan · ${slot} · ${t.mins} min`,status:'Cash on the day',total:money(t.price)});saveState();const ok=await notifyAdmin('massage',{guest:APP.profile.name,email:APP.profile.email,treatment:t.name,slot,duration:`${t.mins} min`,price:money(t.price),payment:'Cash on the day'});closeModal();render();toast(ok?'Massage booked · confirmation sent':'Massage booked · email service needs setup')}
function addPizzaToCart(){if(!APP.profile.email)return toast('Add your email in My Profile first');const qty=Math.max(1,Number(qs('#pizzaQty')?.value||1));APP.cart=[{id:`pizza-${Date.now()}`,type:'pizza',title:`Bali Pizza Party × ${qty}`,qty,unitAmount:249000,currency:'IDR',meta:'26 Jan · 1:00–3:00 PM'}];saveState();closeModal();toast('Pizza added to cart')}
function openPizzaCart(){if(!APP.cart.length)return toast('Your pizza cart is empty');const item=APP.cart[0];const total=item.unitAmount*item.qty;document.body.insertAdjacentHTML('beforeend',`<div class="overlay cartOverlay" onclick="closeCart()"></div><div class="modal cartModal"><div class="modal-card"><div class="eyebrow">Pizza cart</div><h2>${esc(item.title)}</h2><p>${esc(item.meta)}</p><div class="total-box"><span>Total</span><br><strong>${money(total)}</strong></div><div class="pillrow two"><button class="aus-btn red" onclick="checkoutPizza()">Pay with Stripe</button><button class="aus-btn" onclick="closeCart()">Close</button></div></div></div>`)}
function closeCart(){qsa('.cartOverlay,.cartModal').forEach(x=>x.remove())}
async function checkoutPizza(){if(!APP.profile.email)return toast('Add your email first');const item=APP.cart[0];if(!item)return toast('Cart is empty');try{const res=await fetch('/api/create-checkout-session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({qty:item.qty,email:APP.profile.email,name:APP.profile.name})});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||'Checkout unavailable');location.href=data.url}catch(err){console.error(err);toast('Stripe is not configured yet') }}
async function notifyAdmin(type,payload){try{const res=await fetch('/api/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type,payload})});return res.ok}catch(err){console.warn('notify failed',err);return false}}
function openMaps(q){window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`,'_blank')}
function findNear(q){if(!navigator.geolocation)return openMaps(`${q} near Chandra Villas Seminyak`);navigator.geolocation.getCurrentPosition(p=>window.open(`https://www.google.com/maps/search/${encodeURIComponent(q)}/@${p.coords.latitude},${p.coords.longitude},15z`,'_blank'),()=>openMaps(`${q} near Chandra Villas Seminyak`),{timeout:5000})}
function copyText(t){navigator.clipboard?.writeText(t).then(()=>toast('Copied')).catch(()=>toast('Copy unavailable'))}
function addCalendar(title,start,duration=60){const s=new Date(start),e=new Date(s.getTime()+duration*60000),fmt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${fmt(s)}\nDTEND:${fmt(e)}\nSUMMARY:${title}\nLOCATION:${CFG.address}\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='bbb-bali.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function loadWeather(){const el=qs('#weather');if(!el)return;try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=-8.691&longitude=115.166&current=temperature_2m,relative_humidity_2m,precipitation&daily=temperature_2m_max,precipitation_probability_max&timezone=Asia%2FMakassar&forecast_days=7');if(!r.ok)throw new Error('weather');const d=await r.json();el.innerHTML=`<div class="meta">Live Seminyak weather</div><div class="weather-top"><div><div class="temp">${Math.round(d.current.temperature_2m)}°</div><p>${d.current.relative_humidity_2m}% humidity · ${d.current.precipitation}mm rain now</p></div><span class="tag">Bali time</span></div><div class="forecast">${d.daily.time.map((x,i)=>`<div>${new Date(`${x}T00:00:00`).toLocaleDateString(undefined,{weekday:'short'})}<b>${Math.round(d.daily.temperature_2m_max[i])}°</b><small>${d.daily.precipitation_probability_max[i]||0}% rain</small></div>`).join('')}</div>`}catch{el.innerHTML='<div class="meta">Live Seminyak weather</div><h3>Weather unavailable</h3><p>Try again when you have a connection.</p>'}}
async function loadFx(){const providers=[async()=>{const r=await fetch('https://open.er-api.com/v6/latest/AUD');if(!r.ok)throw new Error();const d=await r.json();return{rate:d.rates?.IDR,updated:d.time_last_update_utc}},async()=>{const r=await fetch('https://api.frankfurter.app/latest?from=AUD&to=IDR');if(!r.ok)throw new Error();const d=await r.json();return{rate:d.rates?.IDR,updated:d.date}}];for(const p of providers){try{const data=await p();if(!data.rate)continue;APP.fx=Number(data.rate);const rateEl=qs('#fxrate');if(rateEl)rateEl.textContent=`1 AUD = ${Math.round(APP.fx).toLocaleString()} IDR`;const updated=qs('#fxupdated');if(updated)updated.textContent=`Last updated: ${data.updated||'just now'}`;convertCurrency('aud');return}catch{}}const rateEl=qs('#fxrate');if(rateEl)rateEl.textContent='Live rate unavailable';const note=qs('#fxnote');if(note)note.textContent='Try again later. No conversion has been guessed.'}
function convertCurrency(source){if(!APP.fx)return;const aud=qs('#aud'),idr=qs('#idr');if(!aud||!idr)return;if(source==='aud')idr.value=String(Math.round((Number(aud.value)||0)*APP.fx));else aud.value=((Number(idr.value)||0)/APP.fx).toFixed(2)}
function swapCurrency(){if(!APP.fx)return toast('Live rate is still loading');const aud=qs('#aud'),idr=qs('#idr');if(!aud||!idr)return;const oldAud=Number(aud.value)||0,oldIdr=Number(idr.value)||0;aud.value=(oldIdr/APP.fx).toFixed(2);idr.value=String(Math.round(oldAud*APP.fx))}
function driverSvg(){return `<svg viewBox="0 0 760 300" role="img" aria-label="Illustrated black and red airport transfer car"><rect x="80" y="115" width="540" height="115" rx="34" fill="#252a2d"/><path d="M175 115 L250 60 H470 L540 115Z" fill="#2e3336"/><path d="M265 72 H365 V112 H210Z" fill="#b9d8df"/><path d="M378 72 H460 L520 112 H378Z" fill="#b9d8df"/><path d="M135 130 H245 V220 H135Z" fill="#c92f2f" opacity=".9"/><path d="M460 120 H600 V210 H460Z" fill="#c92f2f" opacity=".85"/><circle cx="210" cy="230" r="46" fill="#17191a"/><circle cx="210" cy="230" r="23" fill="#cbd0d2"/><circle cx="515" cy="230" r="46" fill="#17191a"/><circle cx="515" cy="230" r="23" fill="#cbd0d2"/><circle cx="190" cy="168" r="33" fill="#d73a3a"/><text x="190" y="164" text-anchor="middle" fill="white" font-size="17" font-family="Arial" font-weight="700">DARL'S</text><text x="190" y="184" text-anchor="middle" fill="white" font-size="12" font-family="Arial">BALI</text><text x="350" y="165" fill="white" font-size="18" font-family="Arial" font-weight="700">AIRPORT PICKUP</text><text x="350" y="190" fill="#f1f1f1" font-size="14" font-family="Arial">MADE · BALI</text></svg>`}
function formatDateTime(v){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function attr(s){return esc(s).replace(/`/g,'&#96;')}
function jsEsc(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
function processStripeReturn(){const p=new URLSearchParams(location.search);if(p.get('paid')==='1'&&APP.cart.length){const item=APP.cart[0];APP.plans.push({type:'pizza',title:item.title,meta:item.meta,status:'Paid online via Stripe',total:money(item.unitAmount*item.qty)});APP.cart=[];saveState();history.replaceState({},'',location.pathname+location.hash);toast('Pizza payment successful') }}
function render(){const app=qs('#app');if(!app)return;try{const r=APP.route;if(r==='home')app.innerHTML=homePage();else if(r==='bbb')app.innerHTML=bbbPage();else if(r==='travel')app.innerHTML=travelPage();else if(r==='ready')app.innerHTML=readyPage();else if(r==='bali')app.innerHTML=baliPage();else if(r==='profile')app.innerHTML=profilePage();else if(r==='recovery')app.innerHTML=recoveryPage();else if(r==='pizza-menu')app.innerHTML=pizzaMenuPage();else if(r==='floats')app.innerHTML=floatsPage();else if(r.startsWith('guide-'))app.innerHTML=guidePage(Number(r.split('-')[1]));else{APP.route='home';app.innerHTML=homePage()}renderModal();if(APP.route==='bali')setTimeout(()=>{loadWeather();loadFx()},20)}catch(err){console.error(err);app.innerHTML='<div class="shell"><article class="card"><h3>App loading issue</h3><p>Please refresh. The error has been logged in the browser console.</p></article></div>'}}
window.addEventListener('error',e=>console.error('App error:',e.error||e.message));
window.addEventListener('unhandledrejection',e=>console.error('Promise error:',e.reason));
setInterval(()=>{const c=qs('#countdown');if(c)c.innerHTML=countdownHtml()},1000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{});
processStripeReturn();render();
